### ISSUE TITLE
Laravel 5.6 Installation errors

### ISSUE THREAD

**Issue by scottzirkel** [GrahamCampbell/Laravel-Markdown#103]
Trying to install v9 on Laravel 5.6 and getting the following errors:

```
Problem 1
    - Conclusion: don't install graham-campbell/markdown v9.0.0
    - Conclusion: remove laravel/framework v5.6.0
    - Installation request for graham-campbell/markdown ^9.0 -> satisfiable by graham-campbell/markdown[9.0.x-dev, v9.0.0].
    - Conclusion: don't install laravel/framework v5.6.0
    - graham-campbell/markdown 9.0.x-dev requires illuminate/view 5.1.*|5.2.*|5.3.*|5.4.*|5.5.*-> satisfiable by illuminate/view[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - don't install illuminate/view v5.5.34|don't install laravel/framework v5.6.0
    - Installation request for laravel/framework (locked at v5.6.0, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.0]
```

I've deleted the vendor directory and tried added them one at a time. This is on a 5.5 upgrade to 5.6

**Comment by stephandesouza** [comment]
Already exists two PRs: #102 and #101 

Waiting for the merge too :(

**Comment by scottzirkel** [comment]
Sigh. How did I not go look there first? Thanks for the heads up @stephandesouza!

**Comment by aft3rlife** [comment]
This is quite a big problem, we're about to deploy a new website today and unfortunately we can't install it because of this issue. Any solutions besides forking the repository with the updated version?

**Comment by mediabeastnz** [comment]
Bump!

**Comment by stephandesouza** [comment]
Just citing @GrahamCampbell :
> In 2 weeks, I am upgrading all of my packages to only support 5.5 and 5.6 and PHP 7.1.3+. In the meanwhile I will not be accepting any PRs.

https://github.com/GrahamCampbell/Laravel-Throttle/pull/76#issuecomment-364654566

**Comment by shamimhasan** [comment]
Any update on that issue? Im still waiting for this to release an update.

**Comment by GrahamCampbell** [comment]
V10.0 has now been released. It supports PHP 7.1 or 7.2 and Laravel 5.5 or 5.6.
