### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by TheNew1997** [GrahamCampbell/Laravel-Markdown#105]
Table from markdown not compiled to HTML.

**Comment by GrahamCampbell** [comment]
Tables arn't included in the commonmark spec I'm afraid, but there are some extensions that can be installed that deal with it.

**Comment by laics1984** [comment]
Any laravel extensions you can recommend for table markdown?

**Comment by GrahamCampbell** [comment]
Unrelated to laravel.

**Comment by chrisrhymes** [comment]
I had the same issue and updated my config/markdown.php with the following to resolve it:

```php
'extensions' => [
     \League\CommonMark\Extension\Table\TableExtension::class,
],
```
