### ISSUE TITLE
Configuration: only allow certain markdown

### ISSUE THREAD

**Issue by rienheuver** [GrahamCampbell/Laravel-Markdown#108]
For a project we are reading excel-files and from that we read bold and italic text. We are looking for a way to save bold/italic to a database to later be rendered again. Our current approach is to save the excel values with markdown in it. However, we do not want to parse # for headers and such and we rather not parsing anything else than bold and italic to be certain of security.

So maybe a config can be added to only allow certain tags? Other suggestions for our problem are welcome too of course.

**Comment by GrahamCampbell** [comment]
You will need to rebind the `markdown.environment` on the service container with a custom one. Take a look at the service provider to see what our default binding looks like. The internal environment construction occurs at https://github.com/thephpleague/commonmark/blob/0.18.0/src/Environment.php#L472-L492. You'll want your own replacement for commonmark core extension.
