### ISSUE TITLE
center  tag all clear.

### ISSUE THREAD

**Issue by asterism612** [GrahamCampbell/Laravel-Markdown#110]
<center>![](https://steemitimages.com/0x0/https://c1.staticflickr.com/5/4540/27136302419_acceffb4c0_b.jpg)\t\n</center>

convertoHTML -> "" 

all clear  why?

**Comment by GrahamCampbell** [comment]
This package doesn't do any parsing, we're just using commonmark. Please refer to that package for any queries.
