### ISSUE TITLE
Other possible options for 'html_input'

### ISSUE THREAD

**Issue by Nemesis19** [GrahamCampbell/Laravel-Markdown#111]
Dear developer,

thanks for the packages, it will be very useful for my projects. The docs and config/markdown.php file are not clear about the other possible options for the 'html_input' property. Can you list the other possible choices? since it's a string...I cannot guess it like a simple boolean :)

I love the idea to have strict control over my content using markdown, but I'd like to have a "backdoor" on extra html whenever I will have a particular issue where I need html formatting.

Thanks

**Comment by colinodell** [comment]
The other possible options can be found here: https://commonmark.thephpleague.com/configuration/

![image](https://user-images.githubusercontent.com/202034/43690921-cf60a76a-98e0-11e8-89b8-2ee4a14d7c8e.png)

**Comment by Nemesis19** [comment]
Awesome!

**Comment by skcin7** [comment]
test

**Comment by skcin7** [comment]
aaa

**Comment by skcin7** [comment]
d
