### ISSUE TITLE
suggest: bind function to blade

### ISSUE THREAD

**Issue by sinkcup** [GrahamCampbell/Laravel-Markdown#113]
suggest bind `@markdown` to blade, just like: 

https://github.com/andreasindal/laravel-markdown/blob/3.0.0/src/MarkdownServiceProvider.php#L61

then we can use like this:

```
<article>
    <h1>{{ $post->title }}</h1>

    <section class="content">
        @markdown($post->body)
    </section>
</article>
```

**Comment by GrahamCampbell** [comment]
Thanks for the idea. This has actually been implemented at https://github.com/GrahamCampbell/Laravel-Markdown/pull/112. Any feedback on the PR would be appreciated. :)
