### ISSUE TITLE
first line is being output inside <pre> tags

### ISSUE THREAD

**Issue by GigaMick** [GrahamCampbell/Laravel-Markdown#119]
As said in title. No matter what I do, when I save my markdown to database and render it out, the first line is output within PRE tags rendering any formatting useless. Any ideas?

**Comment by colinodell** [comment]
What does the Markdown look like inside your database?

**Comment by wnateg** [comment]
I encountered this problem. I was able to resolve it by leaving no lines between the blade tags, i.e. @markdown{{ $text}}@endmarkdown

Good luck.

**Comment by GrahamCampbell** [comment]
I wonder if we should trim the first newline character if it exists, before processing?

**Comment by GrahamCampbell** [comment]
All these comments are the reason I originally didn't provide a blade directive, because if I trim the whitespace, it limits people who actually wanted, and if I don't trim it, it doesn't behave in the way a new user might expect.

To avoid all these issues, you can just have .blade.php.md files, and include them like normal.

**Comment by snipe** [comment]
It’s a tough balance, for sure. Would you mind if I opened a PR on the readme to clarify how that should work?

**Comment by GrahamCampbell** [comment]
I think I'm going to update the implementation in v11.0.0 to trim the first newline and last newline, if they exist, for code rendered via the blade tags like this. I think that's gonna be the nicest way to do it. :)

**Comment by GrahamCampbell** [comment]
I've fixed this in the `v11.0.0` release. The contents will be unindented by the indentation level of the `@endmarkdown` directive, before being fed into the markdown renderer, unless there is content with less indentation present, in which case the indentation will be left as is.

**Comment by keloxers** [comment]
thanks !
