### ISSUE TITLE
<p> tags / newlines not being displayed correctly

### ISSUE THREAD

**Issue by ja-heller** [GrahamCampbell/Laravel-Markdown#122]
First of all, thanks for this package.
Two "problems / questions" came up, while using it.

Inside my database I store product descriptions which may contain markdown.
Here's a product description entry, as it's stored inside the database:

```
here goes one line

here another one

here some **markdown** followed by MANY newlines





and here the final content ;o)
```

I'm using this accessor inside the product model to do all the "parsing":

```
    public function getBodyHtmlAttribute()
    {
        return Markdown::convertToHtml(e($this->description));
    }
```

Now, using a template to render it, I get some output like this:
![alt text](https://puu.sh/Cwcqt/982fb8d2fb.png "screenshot")

These two questions came up:

1.  Is there a way to get rid of the `<p></p>` tags around each line?
2.  As you may have noticed, there are many newlines before the bottom line (_and here the final content ;o)_) how can I get these lines being displayed too, since they are inside the database entry?

All the best;

**Comment by GrahamCampbell** [comment]
Yes, in your published config file, change this line to have 2 newlines instead of 1. I think this should do what you want: https://github.com/GrahamCampbell/Laravel-Markdown/blob/master/config/markdown.php#L64. :)

**Comment by GrahamCampbell** [comment]
```php
'soft_break'      => "\n\n",
```

**Comment by ja-heller** [comment]
After changing the config, it doesn't change anything. Accessor and view are for sure the same.
view:

    {!!$text!!}

**Comment by GrahamCampbell** [comment]
Are you sure your config cache isn't stale. Please run `config('markdown')` in your view and check the output has your new config.
