### ISSUE TITLE
Class 'MarkDown' not found

### ISSUE THREAD

**Issue by amustci065** [GrahamCampbell/Laravel-Markdown#124]
**Here is the error I get:**

> ErrorException (E_ERROR)
> Class 'MarkDown' not found (View: C:\wamp64\www\blog\resources\views\blog\show.blade.php)

**Under app.php I have: **

>  'providers' => [
> 
>         GrahamCampbell\Markdown\MarkdownServiceProvider::class,

> 'aliases' => [
> 
>         'Markdown' => GrahamCampbell\Markdown\Facades\Markdown::class,

**While my show.blade.php:**

```
<div class="text">
                                        {!! MarkDown::convertToHtml ($post->body)  !!}

                                    </div>
```

**Comment by GrahamCampbell** [comment]
Please use a lowercase `d`.
