### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by leonekmi** [GrahamCampbell/Laravel-Markdown#125]
Due to [`thephpleague/commonmark`](https://github.com/thephpleague/commonmark) usage, Laravel-Markdown may be vulnerable to XSS attacks.
See https://github.com/thephpleague/commonmark/issues/353

Solution is to update `league/commonmark` to `^0.18.3`.

**Comment by GrahamCampbell** [comment]
Thanks for the report. We're not vulnerable, however, since composer will load the latest version. There would be no point in us increasing our minimum version requirement, because composer could just resolve an older version of this package if it really wanted to get 0.18.2.
