### ISSUE TITLE
CommonMark 1.0

### ISSUE THREAD

**Issue by GrahamCampbell** [GrahamCampbell/Laravel-Markdown#127]
TODO:

* [x] Bump versions
* [x] Update tests
* [x] Check config file
* [x] Handle extension changes
* [x] Docs

**Comment by GrahamCampbell** [comment]
All done. Just waiting on the tests and static analysis to complete, then I'll tag `v11.0.0`. ;)

---

// cc @colinodell

**Comment by colinodell** [comment]
![](https://media1.giphy.com/media/Ge86XF8AVY1KE/giphy.gif?cid=790b76115d1a0e0e6669355332771fb4&rid=giphy.gif)

**Comment by GrahamCampbell** [comment]
> All done. Just waiting on the tests and static analysis to complete, then I'll tag v11.0.0. ;)

Ok, I also want to address the remaining outstanding issue on our tracker, then I'll tag. :P
