### ISSUE TITLE
Compatibility with Laravel 6.0

### ISSUE THREAD

**Issue by narrative1st** [GrahamCampbell/Laravel-Markdown#132]
Brand new install - won't allow me to integrate with 6.0.

Any plans on updating?

**Comment by GrahamCampbell** [comment]
Once Laravel stops making breaking changes to 6.x, yes. I expect early September. :)

**Comment by narrative1st** [comment]
LOL, fair enough. I just rely _heavily_ on this and looking forward to getting it going. Thanks!

**Comment by GrahamCampbell** [comment]
Support for Laravel 6 will land within the next hour. :)
