### ISSUE TITLE
updating from laravel 5.8 - laravel 6.0

### ISSUE THREAD

**Issue by Devrandomuser** [GrahamCampbell/Laravel-Markdown#133]
When updating to laravel 6.0 I get this error all the time:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: don't install graham-campbell/markdown v10.3.1
>     - Conclusion: remove graham-campbell/markdown v10.3.0
>     - Conclusion: don't install graham-campbell/markdown v10.3.0
>     - Installation request for graham-campbell/markdown ^10.3 -> satisfiable by graham-campbell/markdown[10.3.x-dev, v10.3.0, v10.3.1].
>     - Installation request for cviebrock/eloquent-sluggable ^6.0 -> satisfiable by cviebrock/eloquent-sluggable[6.0.0].

composer.json

> "graham-campbell/markdown": "^10.3",

What's the correct version for laravel 6.0?

**Comment by GrahamCampbell** [comment]
No, you'll need `^11.1`. :)

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Markdown/releases
