### ISSUE TITLE
GrahamCampbell/Laravel-Markdown Doesn't work

### ISSUE THREAD

**Issue by shamsulhuda** [GrahamCampbell/Laravel-Markdown#134]
I followed what he explained in-  https://github.com/GrahamCampbell/Laravel-Markdown/blob/master/README.md

1. First, I run this - ```$ composer require graham-campbell/markdown```
2. Then, register with- ```GrahamCampbell\Markdown\MarkdownServiceProvider::class,```
In alias, added this- ```'Markdown' => GrahamCampbell\Markdown\Facades\Markdown::class,```  into ```config/app.php``` file.
3. Then I try to view my content in blade file using this- ```{!! Markdown::convertToHtml($post->content) !!}```

When it wasn't working, Then I run configuration- ```$ php artisan vendor:publish```
Then tried again. unfortunately, it's still doesn't work.

Is there anything i missed? please help me with the proper installation.

**Comment by GrahamCampbell** [comment]
Try running `php artisan config:cache`.

**Comment by shamsulhuda** [comment]
@GrahamCampbell Still show blank page

**Comment by DarkStoorM** [comment]
But what exactly is happeninng?
- Be sure to have no indentation when parsing markdown:
```
@markdown
{{ $yourContent }}
@endmarkdown
```

- You can also use `@markdown($content)`
- or `@markdown {{ $yourContent }} @endmarkdown`

of course, if I understood your issue correctly

**Comment by GrahamCampbell** [comment]
You should require the latest version, `^11.1`. It will work on Laravel 5.5-6.x.
