### ISSUE TITLE
How can i install Laravel Markdown when am using php 7.1 and laravel 5.2

### ISSUE THREAD

**Issue by BYUKALPHA** [GrahamCampbell/Laravel-Markdown#135]
How can i install Laravel Markdown when am using php 7.1 and laravel 5.2

 Problem 1
    - illuminate/view v6.4.1 requires php ^7.2 -> your PHP version (7.1.32) does not satisfy that requirement.
and I don't want to upgrade my php version now

Help me

**Comment by GrahamCampbell** [comment]
You should upgrade to Laravel 5.5 LTS or Laravel 6 as soon as possible.

It is possible to install this package (`^9.0`) on Laravel 5.2, but there are known security vulnerabilities that will not be fixed due to it requiring an old version of commonmark.

**Comment by BYUKALPHA** [comment]
Ok thank you
