### ISSUE TITLE
" < are escaped inside pre

### ISSUE THREAD

**Issue by ahmadyousefdev** [GrahamCampbell/Laravel-Markdown#138]
Hi, I have this example code that I want to show inside a pre code ` ``` ` : 

```
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class Blog extends Model
{
    public function attachments()
    {
        return $this->hasMany('App\Attachment');
    }
}
?>
<div class="layout-medium">
    <div id="primary" class="content-area">
		<p>Test Test Test</p>
		</div>
</div>
```

but when I show it inside `@markdown` in blade it appears like this:

<img width="584" alt="Screen Shot 2020-01-18 at 10 31 48 PM" src="https://user-images.githubusercontent.com/19305025/72669436-acd34180-3a42-11ea-972d-bae0407b23e0.png">

is there a way to disable escaping those symbols ? I tried `'html_input' => 'allow'` but nothing happened.

**Comment by ahmadyousefdev** [comment]
strange,
when I write it like this:
```
@markdown
{{$blog->body}}
@endmarkdown
```
The special letters are escaped,

But when I write it like this:

```
@markdown($blog->body)
```

it doesn't escape those characters ..

?

**Comment by GrahamCampbell** [comment]
I think this is maybe due to Laravel escaping the characters? You need to have your ->body return an HtmlString, or use the blade tags that don't escape HTML.

**Comment by ahmadyousefdev** [comment]
yeah this worked too:

```
@markdown
{!! $blog->body !!}
@endmarkdown
```

**Comment by GrahamCampbell** [comment]
Great.
