### ISSUE TITLE
Class 'League\CommonMark\Extension\Extension' not found

### ISSUE THREAD

**Issue by mwargan** [GrahamCampbell/Laravel-Markdown#139]
Hey there!

On versions 11.2 and up on Laravel 6 I am getting the following error: Class 'League\CommonMark\Extension\Extension' not found

With the following code:

`GrahamCampbell\Markdown\Facades\Markdown::convertToHtml($text)`

**Comment by GrahamCampbell** [comment]
Could you show the whole stack trace please?
