### ISSUE TITLE
auto linking url's

### ISSUE THREAD

**Issue by redbastie** [GrahamCampbell/Laravel-Markdown#144]
does this package provide an option to auto-link url's entered?

**Comment by GrahamCampbell** [comment]
Yes, there's an extension for that: `League\CommonMark\Extension\Autolink\AutolinkExtension::class`. Just dump it in the published config file as per the docs: https://github.com/GrahamCampbell/Laravel-Markdown#commonmark-extensions.

**Comment by redbastie** [comment]
That works great.

One thing, is it possible to have the links use target _blank?

I tried adding `\League\CommonMark\Extension\ExternalLink\ExternalLinkExtension::class,` to the extensions but it didn't seem to make a difference.

**Comment by GrahamCampbell** [comment]
No, that extension (currently) takes no parameters. If you'd like to raise an issue at https://github.com/thephpleague/commonmark/issues, asking if they'd accept a PR to add it, that'd be great (and then implementing it if they say yes).

**Comment by jaap** [comment]
@redbastie I got it working by adding `\League\CommonMark\Extension\ExternalLink\ExternalLinkExtension::class` to the extensions and then adding to the config.
```
    'external_link' => [
        'open_in_new_window' => true
    ]
```

**Comment by bastinald** [comment]
> @redbastie I got it working by adding `\League\CommonMark\Extension\ExternalLink\ExternalLinkExtension::class` to the extensions and then adding to the config.
> 
> ```
>     'external_link' => [
>         'open_in_new_window' => true
>     ]
> ```

@jaap Where did you add this config value exactly?

**Comment by GrahamCampbell** [comment]
@bastinald Please check the readme. :)

**Comment by Corben78** [comment]
As I'm currently trying to get the Heading Permalink Extension included, I stumbled over this issue.
And I'm also struggling with where to place the configuration for the `external_link` setting. It's not obvious enough to me from the readme. I've tried to put it in `config/app.php` or in `config/markdown.php` but neither works. From how I understand it, it could be anywhere in `config/markdown.php`, according to: https://github.com/GrahamCampbell/Laravel-Markdown/blob/1d3740735fa296b09e2f5de9d55c1cb52886b3c9/src/MarkdownServiceProvider.php#L169-L171
Which sets the config for the CommonMark environment without the extension and view setting.
Or I'm doing something else wrong, as the `open_in_new_window` setting has no effect. The link is detected, but it's still opening in the same window.

I'm on Laravel 7 and my `config/markdown.php` file looks like this:
```
    'external_link' => [
        'open_in_new_window' => true
    ],

    'extensions' => [
        League\CommonMark\Extension\ExternalLink\ExternalLinkExtension::class
    ],
```
Can you please point to the place in the readme where it is explained?

**Comment by Corben78** [comment]
Might have been a caching issue... I had to clear all caches, and now it works:
```bash
php artisan config:clear
php artisan cache:clear
php artisan view:clear
```
