### ISSUE TITLE
Documentation: sharing an example of how to load an extension

### ISSUE THREAD

**Issue by braaam** [GrahamCampbell/Laravel-Markdown#147]
A number of extensions are now [included by default with the CommonMark library](https://commonmark.thephpleague.com/1.5/extensions/overview/), and can be easily enabled. For anyone interested, below is an example to enable the table extension. 

In your AppServiceProvider.php, add the following within the **register** function : 

```
        $this->app->resolving('markdown.environment', function (Environment $environment) {
            $environment->addExtension(new TableExtension());
        });
```

Make sure you load the necessary classes:

```
use League\CommonMark\Extension\Table\TableExtension;
use League\CommonMark\Environment;

```

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. You don't need to do this. You can simply follow the config instructions in the README to register extensions: https://github.com/GrahamCampbell/Laravel-Markdown#commonmark-extensions.
