### ISSUE TITLE
Blade @\include not working with v13

### ISSUE THREAD

**Issue by rodrigopedra** [GrahamCampbell/Laravel-Markdown#148]
I migrated a project to version 13 and a markdown template with a blade @\include directive stopped working.

## Steps to reproduce

1. Create a fresh Laravel install
    `laravel new markdown`
2. Require this package 
    `composer require graham-campbell/markdown:^13.1`
3. Delete `welcome.blade.php` view file
4. Create `welcome.md.blade.php` view file with the following contents:
    ~~~
    @include('partial')
    ~~~
5. Create `partial.blade.php` view file with some content, for example:
    ~~~
    Hello World
    ~~~
6. Start project and visit it in the browser

The error displayed is:

> ErrorException: Undefined variable: __env (View: /home/rodrigo/code/webmagic/markdown/resources/views/welcome.md.blade.php) 

As a workaround I reverted to version 12.

I am out of time now to look further in the code and find a reason or solution, but I can give a try on fixing it.

If you have any hint on where I should look, I appreciate.

Thanks for the package.

**Comment by GrahamCampbell** [comment]
Is this issue specifically with v13.1.0, and not with v13.0.0? What happens if you clear the compiled view cache?

**Comment by rodrigopedra** [comment]
Hi @GrahamCampbell , thanks for the response.

Clearing the views with version 13.1 didn't work.

Just tried with version 13.0 and it works.

Will try to skim over the commits to see if I can find the reason.

**Comment by rodrigopedra** [comment]
It seems to be related to the `PathEvaluationTrait`

On this line:

https://github.com/GrahamCampbell/Laravel-Markdown/blob/bd95ce6bb31b9d9732e42907c983b9f8e31c8854/src/View/Engine/PathEvaluationTrait.php#L47

It calls `getRequire` passing both the path and the scope data.

But in Laravel 7 this method only accepts the path and does not extract any data:

https://github.com/laravel/framework/blob/8d4120a3161ba5db16e1f1a63f18c4a803db08df/src/Illuminate/Filesystem/Filesystem.php#L94-L100

Whereas in Laravel 8 (unreleased) it does:

https://github.com/laravel/framework/blob/3de2398034ede61a5f7956d84dc88623f37232f4/src/Illuminate/Filesystem/Filesystem.php#L96-L110

I tried copying Laravel 8's `getRequire` to the project's vendor and if using that it works.

Possible solutions:

- require `laravel/framework:^8` with version 13.1 (might need to release a new version)
- modify `PathEvaluationTrait` to extract the `$data` contents and call `require $path` directly (basically reverting)
- Porting Laravel 8's `getRequire` to Laravel 7 (unlikely as it would be a BC)

Tell me if I can help with any of these or if you have a better solution.

Thanks again for the quick response.

**Comment by GrahamCampbell** [comment]
Thanks for looking into this. The changes made to laravel/framework's master branch were actually made by me, but I forgot that Laravel 6/7 didn't accept that 2nd arg I added. 😆

Does #149 fix your issue?

**Comment by rodrigopedra** [comment]
No problem.

It does, thanks a lot!

**Comment by GrahamCampbell** [comment]
Released v13.1.1. The release should propagate across Packagist within the next 5 minutes.
