### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by Sennik** [GrahamCampbell/Laravel-Markdown#150]
I can't get my head around this:

composer.json

    "require": {
        "php": "^7.2",
        "fideloper/proxy": "^4.0",
        "graham-campbell/markdown": "^13.0",
        "laravel/framework": "^6.0",
        "laravel/helpers": "^1.1",
        "laravel/tinker": "^1.0",
        "laravelcollective/html": "^6.0",
        "league/commonmark": "^1.5",
        "symfony/translation": "4.3.8"
    },

in /config/markdown.php:

    'extensions' => [
        \League\CommonMark\Extension\Table\TableExtension::class
    ],

$txt:

    # This is the Header
    th | th(center) | th(right)
    ---|:----------:|----------:
    td | td         | td

**Then I do this in Blade:**

@markdown( $txt )

Then the table is not parsed correctly but the header is. What am I doing wrong?

**Comment by Sennik** [comment]
What is urgent? Less then 3 days? a week, please tell me ;-)

**Comment by GrahamCampbell** [comment]
Did you clear your config cache?
