### ISSUE TITLE
Don't have br tag when enter a newline

### ISSUE THREAD

**Issue by bocanhcam** [GrahamCampbell/Laravel-Markdown#151]
Hi,
I don't see we have br tag when making a new line so it not go down like the preview I excepted.
This is what I write.
Can you help me solve this?

#### [BÀI 1: Video bài giảng ngữ pháp](https://www.youtube.com/watch?v=afi6dAgB1vM&t=2s)

**Các mẫu ngữ pháp trong bài học:**

-----

 **1. N1　は　N2　です**
 Nghĩa : N1 là N2

 **2. N1　は　N2　じゃありません**
Nghĩa : N1 không phải là N2

**3. N1　は　N2　ですか**
Nghĩa : N1 có phải là N2 không?

**4. N1　も　N2　です**
Nghĩa : N1 cũng là N2

**5. N1 は　N2　の　N3 です**
Nghĩa :N1 là N2 của N3

And this is what I got.

![Screen Shot 2020-09-10 at 16 02 19 (1)](https://user-images.githubusercontent.com/35592955/92707896-e06f2d00-f37f-11ea-8258-d738eb6d4452.png)

```html
<div><h4><a href="https://www.youtube.com/watch?v=afi6dAgB1vM&amp;t=2s">BÀI 1: Video bài giảng ngữ pháp</a></h4>
<p><strong>Các mẫu ngữ pháp trong bài học:</strong></p>
<hr>
<p><strong>1. N1　は　N2　です</strong>
Nghĩa : N1 là N2</p>
<p><strong>2. N1　は　N2　じゃありません</strong>
Nghĩa : N1 không phải là N2</p>
<p><strong>3. N1　は　N2　ですか</strong>
Nghĩa : N1 có phải là N2 không?</p>
<p><strong>4. N1　も　N2　です</strong>
Nghĩa : N1 cũng là N2</p>
<p><strong>5. N1 は　N2　の　N3 です</strong>
Nghĩa :N1 là N2 của N3</p>
</div>
```

**Comment by bocanhcam** [comment]
I fixed it by changing
```php
 'soft_break'      => "\n",
```
to
```php
 'soft_break'      => "<br>",
```
I still don't know what cases for these config 
```block_separator```
```inner_separator```  
```soft_break```
Seem like ```soft_break``` is when we press enter to write a new line. So how about these 2 left?

**Comment by GrahamCampbell** [comment]
Not sure, sorry.

**Comment by colinodell** [comment]
https://commonmark.thephpleague.com/1.5/configuration/ has information on the different options.

`block_separator` is what is output between two consecutive block elements (headings, paragraphs, tables, etc`

`inner_separator` is used to separate things within the blocks.

**Comment by GrahamCampbell** [comment]
@colinodell Thanks so much for jumping in here. 🍻 :)
