### ISSUE TITLE
Strikethrough works in preview mode but not in rendered HTML

### ISSUE THREAD

**Issue by hktang** [GrahamCampbell/Laravel-Markdown#153]
I am using version 11.2. It seems `~~` works as expected in the "preview“ mode, but it was output literally in the HTML. Did I miss something? Thanks for your reply and happy holidays.

## Works
![Screenshot_2020-12-24 APNIS - testNewDeadline](https://user-images.githubusercontent.com/2219830/103079086-8fc1ce00-4616-11eb-85b2-213d69a397bd.png)

## Doesn't work
![InkedScreenshot_2020-12-24 APNIS - testNewDeadline(1)_LI](https://user-images.githubusercontent.com/2219830/103079093-92242800-4616-11eb-84d2-a33395d9fdff.jpg)

**Comment by GrahamCampbell** [comment]
> works as expected in the "preview“ mode

I have no idea what you mean by this.

Please open a fresh issue with something that I can reproduce. Alternatively, you can purchase paid support using the above link.
