### ISSUE TITLE
Best practice for configuring extensions

### ISSUE THREAD

**Issue by extrabright** [GrahamCampbell/Laravel-Markdown#154]
I am trying to figure our what is the best way to customize a CommonMark extension. For example I want to add the [Table of Contents Extenstion](https://github.com/thephpleague/commonmark-ext-table). 

I added the class in the config file and it works great. However, I would like to customize it using the available options for this extension:

```
// Set your configuration
$config = [
    // Extension defaults are shown below
    // If you're happy with the defaults, feel free to remove them from this array
    'table_of_contents' => [
        'html_class' => 'table-of-contents',
        'position' => 'top',
        'style' => 'bullet',
        'min_heading_level' => 1,
        'max_heading_level' => 6,
        'normalize' => 'relative',
        'placeholder' => null,
    ],
];
```

Could you point me to the right direction?

**Comment by GrahamCampbell** [comment]
Thanks for the question.

> I am trying to figure our what is the best way to customize a CommonMark extension. For example I want to add the Table of Contents Extenstion.

The package you link to is not a table of contents extension, but a table exception. Moreover, both of them are dead, and should not be used. You should instead use the implementation of contents provided in the main https://github.com/thephpleague/commonmark package.

> However, I would like to customize it using the available options for this extension:

1. Add `League\CommonMark\Extension\TableOfContents\TableOfContentsExtension::class` to your markdown config file extension array.
2. Add that config literally into the markdown.php config file you have.

The default looks something like:

<img width="893" alt="image" src="https://user-images.githubusercontent.com/2829600/106358229-bacccb00-6302-11eb-866a-0d591fffd7b1.png">

You can literally just append your config to the end:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/2829600/106358233-c7e9ba00-6302-11eb-9ac7-f02436e71fd3.png">
