### ISSUE TITLE
How do I add classes? For example to an list?

### ISSUE THREAD

**Issue by ArneAnka** [GrahamCampbell/Laravel-Markdown#155]
Hi!

Pretty straightforward but how do I add class-names so my css framework kan render properly? I want to add `list-disc` to the `<ul>`

**Comment by colinodell** [comment]
https://github.com/thephpleague/commonmark/issues/605 might answer your question

**Comment by GrahamCampbell** [comment]
Thanks so much @colinodell. Massively appreciate your continual jumping into these issues and helping out. :)

**Comment by ArneAnka** [comment]
Thanks @colinodell 

If anyone is looking to do the same, this is what I did:

1. Create an `Extensions` folder under `App`
2. Create file called `AddListStyleClassesExtension.php` under the newly created folder `App/Extensions`
3. Populate `AddListStyleClassesExtension.php` with:
```
<?php

namespace App\Extensions;

use League\CommonMark\ConfigurableEnvironmentInterface;
use League\CommonMark\Event\DocumentParsedEvent;
use League\CommonMark\Extension\ExtensionInterface;

class AddListStyleClassesExtension implements ExtensionInterface
{
    public function register(ConfigurableEnvironmentInterface $environment): void
    {
            $environment
                ->addEventListener(DocumentParsedEvent::class, new AddListStyleClassesRenderer());
        ;
    }
}
```
4. Create file called `AddListStyleClassesRenderer.php`  under the newly created folder `App/Extensions`
5. Populate `AddListStyleClassesRenderer.php` with:
```
<?php
namespace App\Extensions;

use League\CommonMark\EnvironmentInterface;
use League\CommonMark\Event\DocumentParsedEvent;
use League\CommonMark\Block\Element\ListBlock;

class AddListStyleClassesRenderer {

    /**
     * @param DocumentParsedEvent $e
     *
     * @return void
     */
    public function __invoke(DocumentParsedEvent $e)
    {
        $walker = $e->getDocument()->walker();

        while ($event = $walker->next()) {
            $node = $event->getNode();
            if ($node instanceof ListBlock) {
                $node->data['attributes'] = array('class' => 'list-disc list-inside');
            }
        }
    }

}
```
6. Add the `AddListStyleClassesExtension` class to the `markdown.php`-config file
`'extensions' => [\App\Extensions\AddListStyleClassesExtension::class],`

Done!

**Comment by colinodell** [comment]
Thanks for sharing your solution with others! o/

**Comment by ptmkenny** [comment]
For anybody coming to this from a search engine like I just did, there is a much easier solution now using [Default Attributes](https://commonmark.thephpleague.com/2.3/extensions/default-attributes/).
