### ISSUE TITLE
How to use localized Markdown files in Laravel

### ISSUE THREAD

**Issue by trianity** [GrahamCampbell/Laravel-Markdown#157]
For example, Grav CMS can handle the language version of .md files ( something.en.md , something.fr.md , something.hu.md ) as a standard feature and the question is how to make Laravel-Markdown to load the appropriate localized file into the blade template?

This would be a great feature if the package would load the appropriate language version into the .blade file similar to the standard Laravel language feature.

Or simple use the First Available View method:
[https://laravel.com/docs/8.x/views#view-creators](https://laravel.com/docs/8.x/views#view-creators)

use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\App;

$cur_lang = App::getLocale();
return View::first(['localised.'. $cur_lang, 'en'], $data);

with callback to the proper language?

**Comment by GrahamCampbell** [comment]
I'd be open to reviewing a PR that implements this. :)
