### ISSUE TITLE
Laravel 8 installation problem

### ISSUE THREAD

**Issue by trianity** [GrahamCampbell/Laravel-Markdown#158]
$ composer require graham-campbell/markdown:^13.1

./composer.json has been updated

Running composer update graham-campbell/markdown
Loading composer repositories with package information

Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - graham-campbell/markdown[v13.1.0, ..., 13.2.x-dev] require league/commonmark ^1.5 -> found league/commonmark[1.5.0, ..., 1.6.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires graham-campbell/markdown ^13.1 -> satisfiable by graham-campbell/markdown[v13.1.0, v13.1.1, 13.1.x-dev, 13.2.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by colinodell** [comment]
It sounds like you might currently have `league/commonmark` 2.0.0 installed, but the version of  `graham-campbell/markdown` you're trying to install is not compatible with 2.0.0.  If you use the `-W` flag as mentioned in the output, Composer will downgrade that package to a compatible version for you.

**Comment by raysn0w** [comment]
I have the same issue with a fresh Laravel install.  Using -W doesn't work either.

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/framework ^8.40, found laravel/framework[v8.40.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - laravel/tinker is locked to version v2.6.1 and an update of this package was not requested.
    - laravel/tinker v2.6.1 requires illuminate/console ^6.0|^7.0|^8.0 -> found illuminate/console[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because
 it conflicts with another require.
  Problem 3
    - laravel/sail is locked to version v1.9.0 and an update of this package was not requested.
    - laravel/sail v1.9.0 requires illuminate/console ^8.0|^9.0 -> found illuminate/console[dev-master, v8.0.0, ..., 8.x-dev, 9.x-dev (alias of dev-master)] but these were not loaded, likely because it conf
licts with another require.
`

**Comment by trianity** [comment]
> It sounds like you might currently have `league/commonmark` 2.0.0 installed, but the version of `graham-campbell/markdown` you're trying to install is not compatible with 2.0.0. If you use the `-W` flag as mentioned in the output, Composer will downgrade that package to a compatible version for you.

Hello, I tried to do it, but the Laravel 8 core has already installed `league/commonmark` 2.0.0.
The solution was to clone `GrahamCampbell/Laravel-Markdown`, make offline package from it and correct the composer.json to use the proper `league/commonmark` 2.0.0.

**Comment by bastinald** [comment]
same issue here.

**Comment by subtain-haider** [comment]
am facing same issue

**Comment by 888op** [comment]
> Hello, I tried to do it, but the Laravel 8 core has already installed `league/commonmark` 2.0.0. The solution was to clone `GrahamCampbell/Laravel-Markdown`, make offline package from it and correct the composer.json to use the proper `league/commonmark` 2.0.0.

Hello, did it work to you? If it worked to you, can I know how to do it? I'm still new in using Laravel and I don't know how to install offline package in Laravel. I've tried something like [this](https://stackoverflow.com/questions/45566233/laravel-how-to-manually-install-package-without-composer) but it didn't work for me.
Thank you.

**Comment by trianity** [comment]
> > Hello, I tried to do it, but the Laravel 8 core has already installed `league/commonmark` 2.0.0. The solution was to clone `GrahamCampbell/Laravel-Markdown`, make offline package from it and correct the composer.json to use the proper `league/commonmark` 2.0.0.
> 
> Hello, did it work to you? If it worked to you, can I know how to do it? I'm still new in using Laravel and I don't know how to install offline package in Laravel. I've tried something like [this](https://stackoverflow.com/questions/45566233/laravel-how-to-manually-install-package-without-composer) but it didn't work for me. Thank you.

1. Create a folder /packages/vendor-name/package-name 
2. In this folder setup your Laravel package (or copy of the mentioned package)
Here you can find documentations:
https://laravel.com/docs/8.x/packages
Good tutorial with all necessary steps: https://devdojo.com/devdojo/how-to-create-a-laravel-package
3. In your main Laravel composer.json file setup package access like this:
```
    "repositories": {
        "local01": {
            "type": "path",
            "url": "packages/vendor-name/package-name"
        }
    },
    "require": {
... all other required packages, and at the and: ...
        "vendor-name/package-name": "*"
    },
```
4. After this setup you can modify the package. Don't forget to change the necessary name-space settings in all files of the package.

**Comment by 888op** [comment]
> > > Hello, I tried to do it, but the Laravel 8 core has already installed `league/commonmark` 2.0.0. The solution was to clone `GrahamCampbell/Laravel-Markdown`, make offline package from it and correct the composer.json to use the proper `league/commonmark` 2.0.0.
> > 
> > 
> > Hello, did it work to you? If it worked to you, can I know how to do it? I'm still new in using Laravel and I don't know how to install offline package in Laravel. I've tried something like [this](https://stackoverflow.com/questions/45566233/laravel-how-to-manually-install-package-without-composer) but it didn't work for me. Thank you.
> 
> 1. Create a folder /packages/vendor-name/package-name
> 2. In this folder setup your Laravel package (or copy of the mentioned package)
>    Here you can find documentations:
>    https://laravel.com/docs/8.x/packages
>    Good tutorial with all necessary steps: https://devdojo.com/devdojo/how-to-create-a-laravel-package
> 3. In your main Laravel composer.json file setup package access like this:
> 
> ```
>     "repositories": {
>         "local01": {
>             "type": "path",
>             "url": "packages/vendor-name/package-name"
>         }
>     },
>     "require": {
> ... all other required packages, and at the and: ...
>         "vendor-name/package-name": "*"
>     },
> ```
> 
> 1. After this setup you can modify the package. Don't forget to change the necessary name-space settings in all files of the package.

Hi, thank you for your response, but it is still an error for me that the class not found from config/app.php. Maybe I miss something, so I will try it later. Thank You very much once again.

**Comment by yannoff** [comment]
Had the same problem, here is the workaround I found (not ideal, but simple):

1. Remove the composer lock file

    ```bash
    rm composer.lock
    ```
2. Require the package

    ```bash
    composer req graham-campbell/markdown:^13.1
    ```

**Comment by GrahamCampbell** [comment]
Thank you everyone. This is an issue/limitation with composer. It is not smart enough to downgrade commonmark to allow installation of this package. The best thing to do for now is to add this package to your composer.json by hand and then run composer update. I will be releasing a new major version of this package soon, switching from commonmark v1 to v2, so stay tuned.
