### ISSUE TITLE
Markdown output does not print well if the text continues without any space.

### ISSUE THREAD

**Issue by lc-salman-ahmad** [GrahamCampbell/Laravel-Markdown#161]
**PHP version**: 7.4
**Laravel version**: 8.4

**Description**
Please help me how can I solve this problem? 

As soon as I am doing Markdown::convertToHtml() the output does not print well. It's going out of the box if the text continues without any space. See the output below -

![image](https://user-images.githubusercontent.com/94098786/141766065-68dde362-0bbd-4cfa-a77e-407d93356f1d.png)

Thanks in advance
Regard Salman Ahmad

**Comment by colinodell** [comment]
Hi @lc-salman-ahmad,

It looks like the Markdown is converted to the proper HTML contents, but that your `<pre><code>` tags do not have any overflow or text wrapping styles applied, which makes it run off the page.  Please consider adding those styles to better format the display of those tags.

**Comment by lc-salman-ahmad** [comment]
Hi @colinodell 

Thanks for your quick reply. Yes, Markdown seems to be working fine only the problem is where the text has been written without any space. Below is my `<pre>` and `<pre><code>` style for your reference.

`pre {
    display: block;
    font-size: 87.5%;
    color: #212529;
    margin-top: 0;
    margin-bottom: 1rem;
    overflow: auto;
}`

`pre code {
    font-size: inherit;
    color: inherit;
    word-break: normal;
}`

I also tried word-break:break-all; and word-break:break-word but nothing seems to be working.

Please suggest what I need to change into this to fix this issue because I am not an expert in styling CSS.

Regards,
Salman

**Comment by GrahamCampbell** [comment]
Thanks everyone. I'm going to close this out since this is a bit out of scope of the purpose of the issue tracker. I'd encourage you to book some time with a frontend engineer to get this resolved quickly.
