### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.         Installation failed, reverting ./composer.json to its original content.

### ISSUE THREAD

**Issue by yazan-1999** [GrahamCampbell/Laravel-Markdown#164]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install graham-campbell/markdown v13.1.2
    - Conclusion: don't install graham-campbell/markdown v13.1.1
    - Conclusion: don't install graham-campbell/markdown v13.1.0
    - Conclusion: don't install graham-campbell/markdown v13.0.0
    - Installation request for laravel/framework (installed at v8.81.0, required as ^8.75) -> satisfiable by laravel/framework[v8.81.0].
    - Installation request for graham-campbell/markdown ^13.0 -> satisfiable by graham-campbell/markdown[13.1.x-dev, v13.0.0, v13.1.0, v13.1.1, v13.1.2].
    - Conclusion: remove league/commonmark 2.2.1
    - graham-campbell/markdown 13.1.x-dev requires league/commonmark ^1.5 -> satisfiable by league/commonmark[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.x-dev, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.x-dev].
    - Can only install one of: league/commonmark[2.2.1, 1.5.0].
    - Can only install one of: league/commonmark[2.2.1, 1.5.1].
    - Can only install one of: league/commonmark[2.2.1, 1.5.2].
    - Can only install one of: league/commonmark[2.2.1, 1.5.3].
    - Can only install one of: league/commonmark[2.2.1, 1.5.4].
    - Can only install one of: league/commonmark[2.2.1, 1.5.5].
    - Can only install one of: league/commonmark[2.2.1, 1.5.6].
    - Can only install one of: league/commonmark[2.2.1, 1.5.7].
    - Can only install one of: league/commonmark[2.2.1, 1.5.8].
    - Can only install one of: league/commonmark[2.2.1, 1.5.x-dev].
    - Can only install one of: league/commonmark[2.2.1, 1.6.0].
    - Can only install one of: league/commonmark[2.2.1, 1.6.1].
    - Can only install one of: league/commonmark[2.2.1, 1.6.2].
    - Can only install one of: league/commonmark[2.2.1, 1.6.3].
    - Can only install one of: league/commonmark[2.2.1, 1.6.4].
    - Can only install one of: league/commonmark[2.2.1, 1.6.5].
    - Can only install one of: league/commonmark[2.2.1, 1.6.6].
    - Can only install one of: league/commonmark[2.2.1, 1.6.7].
    - Can only install one of: league/commonmark[2.2.1, 1.6.x-dev].
    - Installation request for league/commonmark (installed at 2.2.1) -> satisfiable by league/commonmark[2.2.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by GrahamCampbell** [comment]
v14.0.0 has now been released, with support for CommonMark 2, and Laravel 8 & 9.
