### ISSUE TITLE
Laravel 9 Support?

### ISSUE THREAD

**Issue by jseycom** [GrahamCampbell/Laravel-Markdown#165]
Can Laravel 9 be added?

**Comment by maulayyacyber** [comment]
i same the problem when upgrade for Laravel 9.

**Comment by marcroberts** [comment]
I too am looking forward to a stable v14 release to support Laravel 9. In the meantime I've been using version `14.0.x-dev` to test upgrading to Laravel 9 and I've had no problems with this so far

**Comment by thannaske** [comment]
I can confirm that the v14 branch works fine on my application. I needed to re-publish the configuration file as I encountered a ValidationException that said: Unexpected item 'commonmark'

Furthremore, the `convertToHtml` function has been deprecated in favor of `convert`.

**Comment by mtstnt** [comment]
Confirmed what @thannaske and @marcroberts said above. It worked with 14.0.x-dev

Here's what I did:
1. `composer require graham-campbell/markdown:14.0.x-dev`  
2. Remove `config/markdown.php`
3. `php artisan vendor:publish` and select this package.

**Comment by GrahamCampbell** [comment]
v14.0.0 has now been released, with support for CommonMark 2, and Laravel 8 & 9.
