### ISSUE TITLE
Update README or facade method

### ISSUE THREAD

**Issue by jasonmccreary** [GrahamCampbell/Laravel-Markdown#166]
For the `14.0` branch, the README shows `Markdown::convertToHtml` returning a string. However, it now returns a `RenderedOutput` object which needs `getContent()` called.

Either the README method should be updated to chain `getContent()` or the underlying method should to continue returning a `string`.

I'm glad to PR this if you let me know which direction you prefer. Personally, I'd like to keep the `string` return for better DX and to avoid breaking changes.

**Comment by GrahamCampbell** [comment]
v14.0.0 has now been released, with support for CommonMark 2, and Laravel 8 & 9. The docs have now caught up. :)
