### ISSUE TITLE
Update title

### ISSUE THREAD

**Issue by peter-mw** [GrahamCampbell/Laravel-Markdown#17]
![image](https://cloud.githubusercontent.com/assets/5698247/5603929/0290440a-93a5-11e4-88f4-852ccbbec3fa.png)

Hi, i want to use Parsedown wrapper for Laravel 5 

Is this a Parsedown wrapper or League\Commonmark as its stated in the Readme?

**Comment by VladShcherbin** [comment]
@peter-mw 
**2.0** version (for Laravel 4) is a Parsedown wrapper
**3.0** version (for Laravel 5) is a Commonmark wrapper

**Comment by peter-mw** [comment]
@VladShcherbin thanks for the info 

Seems I will use v3.0 besides its not based on Parsedown 

Hope this issue https://github.com/erusev/parsedown/issues/213 goes resolved and this lib to be using Parsedown as it is the one of the fastest markdown processors

**Comment by GrahamCampbell** [comment]
Yeh, you're correct. It should say CommonMark now. CommonMark is far better written than parsedown, although it might not do as well in a benchmark, but in a large system, this different is so small, you won't notice.

**Comment by peter-mw** [comment]
@GrahamCampbell 
League\Commonmark is written in more verbose style, but in terms of performance it cant beat Parsedown

**Comment by GrahamCampbell** [comment]
"verbose" doesn't really cut it. It's a totally different architecture.

**Comment by GrahamCampbell** [comment]
I would recommend anyone to switch to commonmark, hence why I've switched this package to it. It's far superior.

**Comment by GrahamCampbell** [comment]
Parsedown is probably struggling to be commonmark compliant due to it's optimization for performance leading to it being poorly architected. Sorry. :(

**Comment by peter-mw** [comment]
Yes you are certainly right that is better written and the architecture is better

But do we have to include lib that is made of 120 fifes instead of one file as in parsedown?

**Comment by GrahamCampbell** [comment]
I don't understand why that matters?

**Comment by peter-mw** [comment]
It maybe does not. I am deploying some Laravel 5 stuff on shared hostings with limited resources and the number of files loaded on request is like 315+ and i want to keep those numbers down

**Comment by GrahamCampbell** [comment]
Laravel can compile the files to one file if you want.

**Comment by GrahamCampbell** [comment]
Laravel uses a package that I'm co-maintaining atm under the hood to do this: https://github.com/mtdowling/ClassPreloader.

**Comment by peter-mw** [comment]
Thanks i will look at this, It can be useful in my case

Anyways... its better to use ome file lib than 100 files lib if they do the same and the 1 file fib is faster

**Comment by GrahamCampbell** [comment]
Only if you use it on most of the requests. There is still an overhead for php every time it has to process a file. If it's large an unused, you could end up with slower performance.
