### ISSUE TITLE
Adding extension in v14 / commonmark v2

### ISSUE THREAD

**Issue by hilmanski** [GrahamCampbell/Laravel-Markdown#171]
I got an error when try to make an extension
I name my custom Extension ZoomImageExtension
I tried to use use League\CommonMark\Environment\ConfigurableEnvironmentInterface;
or use League\CommonMark\ConfigurableEnvironmentInterface; same error

Could not check compatibility between App\Extensions\ZoomImageExtension::register(League\CommonMark\Environment\ConfigurableEnvironmentInterface $environment): void and League\CommonMark\Extension\ExtensionInterface::register(League\CommonMark\Environment\EnvironmentBuilderInterface $environment): void, because class League\CommonMark\Environment\ConfigurableEnvironmentInterface is not available

```
<?php

namespace App\Extensions;

use League\CommonMark\Event\DocumentParsedEvent;
use League\CommonMark\Environment\ConfigurableEnvironmentInterface;
use League\CommonMark\Extension\ExtensionInterface;
use League\CommonMark\Inline\Element\Image;

class ZoomImageExtension implements ExtensionInterface
{
    public function register(ConfigurableEnvironmentInterface $environment): void
    {
        $environment->addEventListener(DocumentParsedEvent::class, [$this, 'onDocumentParsed']);
    }

    public function onDocumentParsed(DocumentParsedEvent $event) 
    {

    }
}
```

**Comment by jhull** [comment]
Getting the same error here. As it's been a year, I wonder if there has been some solution ... ?

**Comment by GrahamCampbell** [comment]
I think this is an issue with your extension code - you are using the v1 style. This library definitely works with extensions, and indeed loads 2 extensions by default, out of the box. Check out the code over in the commonmark repo for how to correctly implement extensions. Reading the code over there will explain how they work better than I can without knowing the full context of what you are trying to do.

**Comment by GrahamCampbell** [comment]
https://github.com/thephpleague/commonmark/tree/2.4.1/src/Extension
