### ISSUE TITLE
Livewire support?

### ISSUE THREAD

**Issue by thelar** [GrahamCampbell/Laravel-Markdown#172]
Not really an issue but wanted to ask whether this can be used with Livewire components? Been trying for days to get an EasyMDE editor into the Profile Information Form of a Laravel 9 App I'm building, but just can't get it to work - I tried toast-ui first without any luck either. My App uses Fortify/Livewire/Jetstream.

**Comment by m5kh6n77** [comment]
I also have this problem i think this  I think it problem with Livewire

**Comment by GrahamCampbell** [comment]
Yeh, probably. I've not tried this with Livewire. 🤷
