### ISSUE TITLE
Unexpected item 'commonmark'.

### ISSUE THREAD

**Issue by Pardeepjakhar** [GrahamCampbell/Laravel-Markdown#173]
I have update my project from laravel 8 to laravel 9. I also update graham-campbell/markdown version to 14.0 according to laravel 9 upgrade but after that i also getting  this error. Please help me to solve this issue.

![image_2022_11_24T07_58_54_056Z](https://user-images.githubusercontent.com/60398309/203725863-5da13f28-a1d6-430e-afb4-c32e68ac6b78.png)

**Comment by ottosmops** [comment]
I had the same error, just update the config file (compare it with the config file in this repo)

**Comment by GrahamCampbell** [comment]
I think the issue here is likely the config file is bad. Did you replace the config file with the new format, when you upgraded?
