### ISSUE TITLE
Call to undefined method [package]

### ISSUE THREAD

**Issue by lzhang43** [GrahamCampbell/Laravel-Markdown#19]
The same issue as [this one](https://github.com/ShawnMcCool/laravel-auto-presenter/issues/58)

I'm not sure if Laravel 5 is going to preserve some backward compatibility for this. I've tried to lock my Laravel version at `dev-master#846c935194a036901ba6b4397c8897fa51e19111`. However, it gives me new errors like "Call to undefined function env()"...

Is it possible for you to remove the following line in `@dev` for now?

```
$this->package('graham-campbell/markdown', 'graham-campbell/markdown', __DIR__);
```

Thanks a lot.

**Comment by GrahamCampbell** [comment]
Yeh, this issue is exactly the same.

**Comment by GrahamCampbell** [comment]
The same as https://github.com/GrahamCampbell/Laravel-Markdown/issues/18 rather.

**Comment by GrahamCampbell** [comment]
It's different to the auto-presenter one because auto-presenter was not using any of the stuff that got removed.

**Comment by lzhang43** [comment]
@GrahamCampbell I understand. Thanks anyway.
