### ISSUE TITLE
Links break render

### ISSUE THREAD

**Issue by DavidLemayian** [GrahamCampbell/Laravel-Markdown#21]
If content you want to render contains a link e.g `[Example](http://example.com)`, the following error is thrown:

```log
ERROR: exception 'ErrorException' with message 'preg_match() expects parameter 2 to be string, array given' in /home/ubuntu/laravel-app/vendor/erusev/parsedown-extra/ParsedownExtra.php:228
```

**System:**
graham-campbell/markdown - v2.0.7
laravel/framework - v4.2.16

**Comment by GrahamCampbell** [comment]
I think this is already fixed in `2.0.*@dev`. Please confirm. If it's working, I'll tag v2.0.8.

**Comment by DavidLemayian** [comment]
Yes it does. Thank you @GrahamCampbell.

**Comment by GrahamCampbell** [comment]
:beers:
