### ISSUE TITLE
example of use?

### ISSUE THREAD

**Issue by mimoo** [GrahamCampbell/Laravel-Markdown#22]
Hi, having never used a facade it is not clear how to use your library

an example would be great!

thanks

**Comment by GrahamCampbell** [comment]
@mimoo You don't need to use a facade if you don't want to. I'd actually recommend against using it.


Example using dependency injection:

```php
<?php

namespace Foo;

use League\CommonMark\CommonMarkConverter;

class Bar
{
    protected $markdown;

    public function __constructor(CommonMarkConverter $markdown)
    {
        $this->markdown = $markdown;
    }

    public function baz()
    {
        return $this->markdown->convertToHtml('markdown goes here');
    }
}
```

**Comment by james2doyle** [comment]
Facade example:

```php
<?php namespace App\Classes;

use Markdown;

class SomeClass
{
  public function render($string) {
    // once the facade is being "used", call the convertToHtml static method
    echo Markdown::convertToHtml($string);
  }
}
```

**Comment by GrahamCampbell** [comment]
`use Markdown;`

I'd always recommend using the FQCN there so you know what it is is actually going on. :)

**Comment by KannKhy** [comment]
Hello GrahamCampbell, when I run composer require graham-campbell/markdown I got error below:
Package socialnorm/socialnorm is abandoned, you should avoid using it. No replacement was suggested.
Package socialnorm/soundcloud is abandoned, you should avoid using it. No replacement was suggested.
Package socialnorm/instagram is abandoned, you should avoid using it. No replacement was suggested.
Package socialnorm/google is abandoned, you should avoid using it. No replacement was suggested.
Package socialnorm/linkedin is abandoned, you should avoid using it. No replacement was suggested.
Package socialnorm/github is abandoned, you should avoid using it. No replacement was suggested.
Package socialnorm/facebook is abandoned, you should avoid using it. No replacement was suggested.
Package adamwathan/eloquent-oauth is abandoned, you should avoid using it. No replacement was suggested.
Package adamwathan/eloquent-oauth-l5 is abandoned, you should avoid using it. No replacement was suggeste
d.
Please help me to solve this problem. Thank you!

**Comment by GrahamCampbell** [comment]
Seems unrelated to this package. You have other packages you have installed that are abandoned.
