### ISSUE TITLE
Russian text in markdown

### ISSUE THREAD

**Issue by mikield** [GrahamCampbell/Laravel-Markdown#23]
Used in Laravel 4 and worked fine.

Now in Laravel 5 I have some problems.  Russian text with `<code>` renders like: 
`<li>Из: твоя <code>оя featu</code> ветка</li>`

But must render like:

`<li>Из: твоя <code>feature</code> ветка </li>`

It repeats some symbols.

When in line are only english sybmols - is OK

**Comment by GrahamCampbell** [comment]
Please report this issue on https://github.com/thephpleague/commonmark.
