### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by lukasoppermann** [GrahamCampbell/Laravel-Markdown#24]
Hey,

is there an easy way to add extensions to this using the `addInlineParser` method? Maybe this could somehow be done using the published config?

**Comment by GrahamCampbell** [comment]
Easiest way is to just extend my service provider and override the `registerMarkdown` method.

**Comment by john052** [comment]
I also want to add extensions. I could extend the service provider like you said, but was wondering if you could simply add a public accessor to the `DocParser` on `CommonMarkConverter`. From `DocParser` you can get the `CommonMark Environment` and extend from there.

Or better yet (?), save the environment on `CommonMarkConverter' and add a public accessor there.
Then you can extend using
```
    app('markdown')->getEnvironment()->addInlineParser(new CustomParser());
```

**Comment by michellaurent** [comment]
@GrahamCampbell: Do you have an example of integrating one of the custom parsers/renderers available on the [league/commonmark website](http://commonmark.thephpleague.com/customization/overview/) ?

It would be nice if we could have a few arrays in the config files for InlineRender, InlineParser, BlockRenderer like we have in Laravel config/app ...

**Comment by GrahamCampbell** [comment]
Yeh, alt-three/emoji is an example. :)

**Comment by GrahamCampbell** [comment]
https://github.com/AltThree/Emoji

**Comment by michellaurent** [comment]
@GrahamCampbell Thanks. Works fine for me

**Comment by GrahamCampbell** [comment]
We now support proper extensions btw.

https://github.com/GrahamCampbell/Laravel-Markdown/blob/master/config/markdown.php#L42
