### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by sdeering** [GrahamCampbell/Laravel-Markdown#25]
Hi mate,
Is it possible to call the Markdown fascade directly in a controller to convert or does this package only convert files?
Thanks,
Sam

**Comment by sdeering** [comment]
Ps - your doing a great job!

**Comment by sdeering** [comment]
Nevermind i've seen it in the src code.

```
Markdown::convertToHtml($github_readme);
```

Maybe add a quick sentence to the readme?

**Comment by GrahamCampbell** [comment]
It is in the readme, under usage.
