### ISSUE TITLE
markdown doesn't render in a blade section

### ISSUE THREAD

**Issue by erikbelusic** [GrahamCampbell/Laravel-Markdown#28]
not sure if this is supported or not, or if it can be supported, but i am trying to render markdown in a blade section such as

file - welcome.md.blade.php
```
@extends('layouts.default')

@section('content')
    # home
@stop
```

when the view is rendered, it is plain text. is this by design, or a bug?

**Comment by GrahamCampbell** [comment]
It should be rendered The fact that it's in a section has nothing to do with us.. We render blade files after they're been run by php, at runtime. So we don't know what the original blade looked like.

**Comment by erikbelusic** [comment]
thoughts on trouble shooting? is this an issue to my set up, or a package issue?

all i did in my project was spin up a new laravel 5.1 install, pull in your package, add the service provider, and the facade. made a master template, made a section. added what you see above to my view and extend the master page.

**Comment by GrahamCampbell** [comment]
Is it due to the indentation?

**Comment by erikbelusic** [comment]
don't think so.... just tried removing the indentation in my view and master page, no change, however in the following example

```
# header 1
**strong text?**
@extends('layouts.default')
@section('content')
# header 1
**strong text?**
@stop
```

lines 1 and 2 are processed and converted to html, while lines 5 and 6 are not.... super odd. i also tried different combinations of adding .md.blade.php to all my file names, meaningm both master page and view, just master page, and just view, and still no luck

**Comment by martin-woolstenhulme** [comment]
I think the answer may be as simple as adding an extra new line after the section tags. For example do this:

```
@section('content')

# header 1
**strong text?**

@stop
```

Markdown at times needs an extra new line to delimit between separate structure.

**Comment by GrahamCampbell** [comment]
@martin-woolstenhulme has the solution. Thank you. :)

**Comment by martin-woolstenhulme** [comment]
A little more experimentation shows that indentation is important too, when it comes to the HTML tags in the template. For example

```
<html>
    <head>
        <title>App Name - @yield('title')</title>
    </head>
    <body>
        @section('sidebar')
            This is the master sidebar.
        @show

<div class="container">
    @yield('content')
</div>
    </body>
</html>
```

This will yield markdown that is contained within the `<div>` tags, which is probably the intent. However if you do this

```
<html>
    <head>
        <title>App Name - @yield('title')</title>
    </head>
    <body>
        @section('sidebar')
            This is the master sidebar.
        @show

    <div class="container">
        @yield('content')
    </div>
    </body>
</html>
```

You'll get the `<div>` tags in `<pre><code>` tags, which is probably not the intent. In my example, I also got the `</body>` tag as pre-formatted code, which is another sign that you're not getting what you intended.

Unfortunately, in this case, indentation conventions for readability upset the sequence of template processing, so you'll have to tolerate some poorly formatted code.
