### ISSUE TITLE
GitHub Markdown API

### ISSUE THREAD

**Issue by jbrooksuk** [GrahamCampbell/Laravel-Markdown#29]
A driver based system so you can use CommonMark or GitHub's Markdown API.

**Comment by GrahamCampbell** [comment]
Or indeed parsedown for those that way inclined, lol.

**Comment by jbrooksuk** [comment]
:wink:

**Comment by GrahamCampbell** [comment]
Replaced by https://github.com/AltThree/Emoji.

**Comment by jbrooksuk** [comment]
:boom:
