### ISSUE TITLE
Inline UserHandleParser

### ISSUE THREAD

**Issue by pfeiferchristopher** [GrahamCampbell/Laravel-Markdown#32]
So I extended this for a UserHandleParser below but it doesn't make the changes.
```php
<?php

namespace App\Extensions\Markdown;

use League\CommonMark\ContextInterface;
use League\CommonMark\Inline\Element\Link;
use League\CommonMark\Inline\Parser\AbstractInlineParser;
use League\CommonMark\InlineParserContext;

class UserHandleParser extends AbstractInlineParser
{
    public function getCharacters() {
        return array('@');
    }

    public function parse(ContextInterface $context, InlineParserContext $inlineContext) {
        $cursor = $inlineContext->getCursor();

        // The @ symbol must not have any other characters immediately prior
        $previousChar = $cursor->peek(-1);
        if ($previousChar !== null && $previousChar !== ' ') {
            // peek() doesn't modify the cursor, so no need to restore state first
            return false;
        }

        // Save the cursor state in case we need to rewind and bail
        $previousState = $cursor->saveState();

        // Advance past the @ symbol to keep parsing simpler
        $cursor->advance();

        // Parse the handle
        $handle = $cursor->match('/^\w+\W\w+/');
        if (empty($handle)) {
            // Regex failed to match; this isn't a valid Twitter handle
            $cursor->restoreState($previousState);

            return false;
        }

        $profileUrl = url('members/' . $handle);

        $inlineContext->getInlines()->add(new Link($profileUrl, '@'.$handle));

        return true;
    }
}
```
I've bootstrapped the parser into Markdown with a ServiceProvider as seen below.
```php
    $environment = Environment::createCommonMarkEnvironment();
    $environment->addInlineParser( new UserHandleParser() );
```
But it doesn't parse my text case on render.

Any ideas?

**Comment by pfeiferchristopher** [comment]
Okay now I think it is properly attached because now in `AppServiceProvider.php` I have the following
```php
    $environment = $this->app->make('markdown.environment');
    $environment->addInlineParser( new UserHandleParser() );
```
Which should work since `->addInlineParser()` doesn't throw any exceptions. But it still isn't parsing `@Trinyx` into a link as it should.

**Comment by GrahamCampbell** [comment]
You don't need to do anything like that.

**Comment by GrahamCampbell** [comment]
See how to do this here: https://github.com/AltThree/Emoji/blob/master/src/EmojiServiceProvider.php.

**Comment by GrahamCampbell** [comment]
This is without modifying the service provider of this package at all.

**Comment by pfeiferchristopher** [comment]
'AppServiceProvider' isn't within your package. I had to boot the parser
somewhere.

**Comment by GrahamCampbell** [comment]
You need to add it to your app.php config file.

**Comment by GrahamCampbell** [comment]
You don't need to `boot` it. The resolving container binding deals with that. Consider it a lazy boot so it only boots just before you need to use it, and if you don't use it, it doesn't boot.

**Comment by pfeiferchristopher** [comment]
I add `UserHandleParser.php` to my config/app.php? That doesn't seem right. I think your confused on what I was saying. I added your package's service provider to config/app.php already. I'm saying that I had to find somewhere to to register my custom inline parser. Which I did with `AppServiceProvider` in my providers directory. 

It's working fine now I think the regex was bad or something but it is working.

**Comment by GrahamCampbell** [comment]
> I add UserHandleParser.php to my config/app.php? That doesn't seem right. I think 

No, you add a service provider.

**Comment by pfeiferchristopher** [comment]
Yeah that was what I thought you might say. I'm not building a package myself so there's no need to create it's own service provider for one line of code so I just added to my generic laravel service provider `AppServiceProvider.php` save that one extra file from having to be called.

**Comment by GrahamCampbell** [comment]
DO that then.
