### ISSUE TITLE
check UTF-8 with BOM

### ISSUE THREAD

**Issue by liaosankai** [GrahamCampbell/Laravel-Markdown#34]
If md file is encode UTF-8 with BOM, the first line will not be convert. I try fix as

    public function get($path, array $data = [])
    {
        $bom_content = parent::get($path, $data);
        $contents = str_replace("\xef\xbb\xbf", '', $bom_content);
        return $this->markdown->convertToHtml($contents);
    }

But It not working :(

**Comment by GrahamCampbell** [comment]
Not sure. This isn't really a bug in this package though, so I'm closing.
