### ISSUE TITLE
line breaks not working

### ISSUE THREAD

**Issue by GregoryClaeyssens** [GrahamCampbell/Laravel-Markdown#35]
For some reason this happens:
1x -enter-: nothing
2x -enter-: new paragraph

Why isn't 1x enter a line break? Checked CommonMark spec and there it is a linebreak...
Am I overlooking something?
Thanks in advance

**Comment by GrahamCampbell** [comment]
All the commonmark spec tests pass for this implementation.

**Comment by asterism612** [comment]
space . space  does not line break;
