### ISSUE TITLE
Suggestion for improved documentation/readme

### ISSUE THREAD

**Issue by mortennajbjerg** [GrahamCampbell/Laravel-Markdown#37]
I would suggest that the convertToHtml function is mentioned in the readme.md file. I wasn't sure if the function for converting variables was available as only the views method was described.

To make it easier for new users to decide if this is the right package - and ease development I suggest to just mention this - somewhere:

    Markdown::convertToHtml($my_markdown)

Thank You

**Comment by GrahamCampbell** [comment]
Done. :)
