### ISSUE TITLE
No method to escape user-inputted markdown

### ISSUE THREAD

**Issue by gytdau** [GrahamCampbell/Laravel-Markdown#38]
There's no satisfactory way to escape user-submitted Markdown as it uses the the angle bracket `>` for a block quote, which is escaped by Laravel into `&gt;` by default.

Example:
```
# Title 1

<script src="example.com"></script>

> Blockquote
```

Escaped:

```
# Title 1

&lt;script src=&quot;example.com&quot;&gt;&lt;/script&gt;

&gt; Blockquote
```
The issue here is that the blockquote is no longer recognized as valid Markdown. One solution could be adding an escape function that ignores all right-angle brackets, which would instead convert it to:
```
# Title 1

&lt;script src=&quot;example.com&quot;>&lt;/script>

> Blockquote
```
... which then would result in the expected Markdown, with the blockquote intact.

**Comment by GrahamCampbell** [comment]
Just pass the output through my security package. :)

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Security

**Comment by gytdau** [comment]
The package you mentioned looks like it'd only remove XSS vulnerabilities, but what about other things like the style attribute? That has a lot of potential for misuse, too.

**Comment by GrahamCampbell** [comment]
Just escape the content before parsing it then. :)

**Comment by gytdau** [comment]
You might want to re-read the original issue I posted: escaping it before parsing will not allow the block quotes to be parsed correctly, since they rely on angle brackets, which Laravel converts to `gt;` when escaping.

**Comment by GrahamCampbell** [comment]
Hmm, well, nothing I can really do here. Go and take this up with the people who designed the commonmark spec. ;)

**Comment by gytdau** [comment]
I don't think trying to redesign the spec is the solution, even if it was at all feasible.

Here's another possible solution: a function to escape all the characters except any right angle brackets that are the first character on a line. Would this fit into the package?

If you'd like, I can make it and add a pull request.

**Comment by GrahamCampbell** [comment]
Could it be done from an extension?

**Comment by GrahamCampbell** [comment]
https://github.com/thephpleague/commonmark is designed in a way such that you can register extensions. https://github.com/AltThree/Emoji/blob/master/src/EmojiServiceProvider.php#L97 is en example of how to listen for this package resolving the environment: https://github.com/AltThree/Emoji/blob/master/src/EmojiServiceProvider.php#L97.

**Comment by GrahamCampbell** [comment]
@gytdau Starting from v5.2.0, you'll be able to add `'safe' => true` to enable safe mode. :)

https://github.com/GrahamCampbell/Laravel-Markdown/blob/master/config/markdown.php#L103-L114
