### ISSUE TITLE
can't parse markdown table

### ISSUE THREAD

**Issue by sinkcup** [GrahamCampbell/Laravel-Markdown#39]
## demo

`test.md` contents: 

```
# users table

id | name
---|--------
1  | Jim
2  | Lily
```

`routes.php` contents:

```
Route::get('/', function () {
    return view('index');
});
```

## result

GrahamCampbell/Laravel-Markdown can parse "h1", but can't parse "table".

## screenshot

![2015-11-02 14-11-15](https://cloud.githubusercontent.com/assets/4971414/10875285/be339fae-816b-11e5-9f48-8a13a7ced1df.png)

**Comment by GrahamCampbell** [comment]
Tables arn't meant to be supported.

**Comment by GrahamCampbell** [comment]
If you want tables, install https://github.com/webuni/commonmark-table-extension, then add the following 
to the register method of your AppServiceProvider:

```php
        $this->app->resolving('markdown.environment', function (Environment $environment) {
            $environment->addExtension(new TableExtension());
        });
```

Of course, remember to `import use Webuni\CommonMark\TableExtension\TableExtension;` at the top.

After doing that, you should now have table support. You'll need to clear your compiled views to see the change though. ;)
