### ISSUE TITLE
Error when using dependency injection

### ISSUE THREAD

**Issue by jblyberg** [GrahamCampbell/Laravel-Markdown#40]
Getting the following error:

```
BindingResolutionException in Container.php line 745:
Target [League\CommonMark\ElementRendererInterface] is not instantiable.
```

**Comment by GrahamCampbell** [comment]
What exactly are you injecting?

**Comment by GrahamCampbell** [comment]
Have you registered the service provider correctly, and cleared the services.json file?

**Comment by jblyberg** [comment]
In my controller, I'm doing:

```
use Illuminate\Support\Facades\App;
use League\CommonMark\Converter;
```

And then:

```
public function __construct(Converter $converter)
    {
        $this->converter = $converter;
    }
```

**Comment by GrahamCampbell** [comment]
Is the service provider registered correctly?

**Comment by jblyberg** [comment]
In my providers I have:
```
GrahamCampbell\Markdown\MarkdownServiceProvider::class,
```

and in aliases:
```
'Markdown' => GrahamCampbell\Markdown\Facades\Markdown::class,
```

**Comment by GrahamCampbell** [comment]
Does the facade work out of interest?

**Comment by jblyberg** [comment]
Doesn't look like it. Using your example:

```
use GrahamCampbell\Markdown\Facades\Markdown;
Markdown::convertToHtml('foo'); // <p>foo</p>
```

I get:

```
ReflectionException in /Users/jblyberg/git/dl_org-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php line 737:
Class markdown does not exist
```

**Comment by GrahamCampbell** [comment]
Looks like you've not registered the service provider correctly then.

**Comment by GrahamCampbell** [comment]
The test suite for this package proves that the facade does work.

**Comment by jblyberg** [comment]
`GrahamCampbell\Markdown\MarkdownServiceProvider::class,` should be correct though, right?

**Comment by GrahamCampbell** [comment]
Try `'GrahamCampbell\Markdown\MarkdownServiceProvider'`.

**Comment by jblyberg** [comment]
I will keep fiddling. Thanks for the help!

**Comment by GrahamCampbell** [comment]
Are you sure you removed the `services.json` file?

**Comment by jblyberg** [comment]
I just stopped the server, did php artisan config:cache .. cache:clear and that seemed to solve it. Not sure why it didn't work the first time I did it.

**Comment by GrahamCampbell** [comment]
Probably opcache caching the config file. ;)

**Comment by GrahamCampbell** [comment]
Restarting php-fpm probably flushed that cache.

**Comment by GrahamCampbell** [comment]
In future, reloading the service rather than restarting should do it.

**Comment by jblyberg** [comment]
Yup! Cheers!

**Comment by GrahamCampbell** [comment]
np ;)
