### ISSUE TITLE
Strip function?

### ISSUE THREAD

**Issue by BenWoodford** [GrahamCampbell/Laravel-Markdown#41]
Any chance we could get a function to strip all markdown too? Useful for excerpts of posts, etc where you don't want the formatting showing.

**Comment by GrahamCampbell** [comment]
Not sure what you mean?

**Comment by BenWoodford** [comment]
Turns
````
This is a _markdown_ example
````

Into

````
This is a markdown example
````

without any formatting applied

**Comment by GrahamCampbell** [comment]
Just put the output through php's strip_tags function.

**Comment by GrahamCampbell** [comment]
That's still a pretty strange thing for you to be doing though? Why go through the expensive parsing and conversion process only to remove it all?

**Comment by BenWoodford** [comment]
Doesn't work in circumstances where you're just wanting to remove Markdown formatting but not others (BBcode, HTML, etc). :/

**Comment by GrahamCampbell** [comment]
I don't really see why you'd want to do that. Sounds like you need to write your own program from scratch to really do the job properly.

**Comment by alariva** [comment]
I understand that @BenWoodford is willing to be able to display parsed markdown and cleartext as well, by using the same *markdown(ed) source*. This could be useful in some circumstances, but stripping resulting html sounds like enough workaround.

**Comment by bergstar** [comment]
For instance in Laravel Nova there is Markdown field, but like on index page - it is better to show text as-is without markdown. It would be nice to have this feature and its just a natural / normal thing to have.

**Comment by colinodell** [comment]
The underlying library does not plan to support this feature, as Markdown is already a "plain-text" format designed to be perfectly readable without conversion to HTML.

I'd recommend either the `strip_tags()` approach, or if you really want to, [create your own custom renderers](https://commonmark.thephpleague.com/customization/overview/) to modify how the intermediate AST is converted.

**Comment by alariva** [comment]
Agree on @colinodell, sounds like the approach to go about it in compliance with the existing functionality.
