### ISSUE TITLE
Missing first line?

### ISSUE THREAD

**Issue by shealan** [GrahamCampbell/Laravel-Markdown#44]
Markdown from my database TEXT field is being parsed successfully but I am getting some weirdness. Here's the markdown and the result. For some reason it's missing out the first headline. Any ideas?

```
#Hello

So here we go. How about this?

* Some bullets
* Go here
```

Result
```
<p>#Hello
So here we go. How about this?</p>
<ul>
<li>Some bullets</li>
<li>Go here</li>
</ul>
```

**Comment by GrahamCampbell** [comment]
You need an extra newline in your blade before you echo it.

**Comment by GrahamCampbell** [comment]
Laravel strips the newline you think should be there. ;)

**Comment by shealan** [comment]
I'm actually pulling it directly from the db in the model, like so:

```php
	public function getNoteshtmlAttribute() {
		return Markdown::convertToHtml($this->notes);
	} 
```

**Comment by GrahamCampbell** [comment]
You're missing a space after the `#` then. ;)

**Comment by GrahamCampbell** [comment]
> return Markdown::convertToHtml($this->notes);

There are issues with that part specifically, then please report this to common mark.
