### ISSUE TITLE
html is visible in browser

### ISSUE THREAD

**Issue by Foolson** [GrahamCampbell/Laravel-Markdown#46]
Markdown::convertToHtml('_Markdown_')
is rendered as 
<p><em>Markdown</em></p>
in the browser

And if i look in the page source in Chrome it is
&lt;p&gt;&lt;em&gt;Markdown&lt;/em&gt;&lt;/p&gt;

**Comment by GrahamCampbell** [comment]
Probably because you used `{{` instead of `{!!`.

**Comment by GrahamCampbell** [comment]
Actually, there is one thing better we could do here...

**Comment by GrahamCampbell** [comment]
Laravel has that html string stuff.

**Comment by GrahamCampbell** [comment]
On consideration, what we have here is fine.
