### ISSUE TITLE
Extending Markdown syntax to add @[somelink](http://somelink.com)?

### ISSUE THREAD

**Issue by skcin7** [GrahamCampbell/Laravel-Markdown#47]
How can I extend Markdown syntax so that the following code: `@[Go to Microsoft](http://www.microsoft.com)` converts to a link like this: [Go to Microsoft](http://www.microsoft.com).

This is the exact same as any ordinary Markdown link works, except it has an additional '@' character immediately preceding the first opening bracket.

The reason I want to do this is for an @mention system I'm working on.

I found the issue [24](https://github.com/GrahamCampbell/Laravel-Markdown/issues/24) but it's still not really explained how to do it there.

**Comment by GrahamCampbell** [comment]
Feel free to just make a standard extension for php commonmark, then register it in your config. This is how alt-three/emoji works.

**Comment by GrahamCampbell** [comment]
Feel free to check out that package as an example.
