### ISSUE TITLE
Quick Question: Trying to extend Laravel-Markdown for Block Rendering

### ISSUE THREAD

**Issue by tevfik6** [GrahamCampbell/Laravel-Markdown#51]
Hi, 

I'm quite new on Laravel.

I would like to add another rendering/parsing(not sure which one is the best) for Headers. 
So simply, I would like to render `# {Testing This Title}` this to `<h1 id="testing-this-title">Testing This Title</h1>` (Using Laravels, `str_slug` helper)

There are other solutions in order to get id properties for headers. But since I'm trying to learn how to extend a package. If you could show me a starting point with a small code block, i would appreciate.

What I have read before;
https://commonmark.thephpleague.com/customization/block-parsing/
https://commonmark.thephpleague.com/customization/block-rendering/ 

Since I'm not sure where to add these code blockes, I'm stuck.

PS: I have also seen another Issue post here where you recommended an Emoji package but I could not extract the code I need.

Thanks in advance!

Tev.

**Comment by GrahamCampbell** [comment]
You need to create an "extension".

**Comment by GrahamCampbell** [comment]
https://github.com/AltThree/Emoji/blob/master/src/EmojiExtension.php then add that to https://github.com/GrahamCampbell/Laravel-Markdown/blob/master/config/markdown.php#L42.

**Comment by tevfik6** [comment]
Thanks for quick response. 

Where do i need to create my extension file? (https://github.com/AltThree/Emoji/blob/master/src/EmojiExtension.php)

Tev.

**Comment by GrahamCampbell** [comment]
Whereever you want. It doesn;t matter.

**Comment by tevfik6** [comment]
Thanks for the help! :) I implemented what I need. 

Just a minor problem I'm having. I was wondering is there any way to change the order? Seems like core Extensions are running before Custom Extensions. 
I'm kind of overriding the existing Heading parser. Core Heading parser removes the parsed block. Because of that I cannot reach the block. (Returns empty)

Tev.

**Comment by tevfik6** [comment]
Nevermind. 
I've moved my code from Parser to renderer. I've managed the changes i wanted. 

Thanks anyway! 👍 
Tev.

**Comment by pilishen** [comment]
for anyone who may still need this,
actually，nowdays, you can directly use this plugin
[https://github.com/webuni/commonmark-attributes-extension](https://github.com/webuni/commonmark-attributes-extension)
add it into your config entension's array
then good to go
