### ISSUE TITLE
Escape for <canvas> tag

### ISSUE THREAD

**Issue by ColinStadig** [GrahamCampbell/Laravel-Markdown#54]
I'm not able to embed a `<canvas></canvas>` tag within the markdown as it seems to recognize it as text albeit not in quotes like it would normally for other text. I've  noticed that when I inspect the elements using Chrome that <canvas> is not highlighted the same color (purple) as other tags but rather the same coloring as text (black).

`<p><canvas id="myChart" width="400" height="200"></canvas></p>`

Is it possible to escape from the markdown to input the canvas tag as HTML and to return back to the markdown? I am displaying the markdown in my view.blade.php file as follows: 
`{!! Markdown::convertToHtml(e($post->body)) !!}`

(in this example, body represents the text used for a blog entry)

***UPDATE*** 
"The issue is that Markdown was created long before the <canvas> tag (during the HTML 4 and XHTML 1 days) and most Markdown implementations do not include that tag in their list of "block-level HTML elements." - Waylan from Stackoverflow

Not sure where to begin... would this be worth the effort to update the markdown code to have included?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. You'd need to write an extension for this. The readme of this package is getting an update to explain that extension exist better, and to point to the league docs. :)
