### ISSUE TITLE
Nested list hides content

### ISSUE THREAD

**Issue by cedricve** [GrahamCampbell/Laravel-Markdown#56]
Helle Graham

I'm using version 2.1.0 for Laravel 4.2, and it looks that when I'm using a nested list in my markdown file, all the content below is lost. Do you have any idea?

E.g.

```
* test
 * test 2
* test
 * test 2

hello
```

The result is that the list is shown correctly, but the text hello is missing.

**Comment by GrahamCampbell** [comment]
Sorry, no idea. I don't write the parsers.

**Comment by cedricve** [comment]
Great support thanks :+1:

**Comment by GrahamCampbell** [comment]
```
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
```

**Comment by cedricve** [comment]
@GrahamCampbell that's great, I think you need some people skills, that would make you better developer :) If you don't want to get bothered by humans, please make this repository private or crawl into a pit. Sorry for waisting your time :)

**Comment by vinkla** [comment]
@cedricve Graham spends countless hours making Laravel framework and several other open source projects awesome. He probably get around hundred of these questions everyday. Please try be humble and appreciate his work.

The README states:

> There are other classes in this package that are not documented here (such as the engine and compiler classes). This is because they are not intended for public use and are used internally by this package.

This is because this is a Laravel wrapper of https://github.com/thephpleague/commonmark

**Comment by GrahamCampbell** [comment]
Sorry, but I'm not interested in providing free support for issues outside of the scope of my packages on these issue trackers, and you can't really expect that.

**Comment by cedricve** [comment]
@vinkla I agree 100% with that, but answering like that is kinda rude :) And doesn't makes you popular, neverthless the great work you do. Sorry no respect.

**Comment by vinkla** [comment]
@cedricve how is it rude? The "sorry, no idea" part?

**Comment by vinkla** [comment]
The comment is both humble and states exactly what he knows.

**Comment by GrahamCampbell** [comment]
I replied to you with the license conditions after being pissed off with your rude response to me simply saying I don't know, it's not my package.

**Comment by cedricve** [comment]
Let's close this conversation @GrahamCampbell, we're waisting our time.
