### ISSUE TITLE
Anchor Tags are ignored

### ISSUE THREAD

**Issue by alexmilde** [GrahamCampbell/Laravel-Markdown#57]
First:
Thanks for this library!

I found a small issue, maybe you can help me out on this.
It seems like anchor-tags are ignored, or am i missing something?

Example:
```
[Help](#Help)
## <a name="Help"></a>Help
```

The anchor is missing in the output.

Thanks again
Alex

**Comment by GrahamCampbell** [comment]
Sorry, but this library has nothing to do with the actual parsing part.
