### ISSUE TITLE
Request: Ability to add classes to images. 

### ISSUE THREAD

**Issue by dancrodev** [GrahamCampbell/Laravel-Markdown#58]
Not sure if it's already implemented, but I can't seem to find it.

Basically, I would want to do something similar to the following

`` ![Image](http://www.example.com/image.png class="img-responsive content-img") ``

It's not something that needs to be overused, but a few images require 1 attribute (img-responsive) while a few others require that one as well as another. 

I know this isn't a true CommonMark implementation, but wondering if I can extend Laravel-Markdown to accomplish this, or perhaps I'm overlooking some easier way to accomplish this. 

Thank you for your time.

**Comment by GrahamCampbell** [comment]
Possible through extensions. :)

**Comment by royduin** [comment]
@dancrodev how did you fix it? Have you created an extension? @GrahamCampbell, can you give an example? I'm playing around with some example code from https://github.com/AltThree/Emoji but can't get it working.

**Comment by royduin** [comment]
Finally found it 💪 

- Add `App\Extensions\Markdown\ResponsiveImageExtension::class` to the `extensions` array in `config/markdown.php`
- Create `app/Extensions/Markdown/ResponsiveImageExtension.php` with:
```
<?php

namespace App\Extensions\Markdown;

use League\CommonMark\Extension\Extension;
use League\CommonMark\Inline\Element\Image;

class ResponsiveImageExtension extends Extension
{
    protected $renderer;

    public function __construct(ResponsiveImageRenderer $renderer)
    {
        $this->renderer = $renderer;
    }

    public function getInlineRenderers()
    {
        return [Image::class => $this->renderer];
    }
}
```

- Create `app/Extensions/Markdown/ResponsiveImageRenderer.php` with:
```
<?php

namespace App\Extensions\Markdown;

use League\CommonMark\ElementRendererInterface;
use League\CommonMark\Inline\Element\AbstractInline;
use League\CommonMark\Inline\Renderer\ImageRenderer;

class ResponsiveImageRenderer extends ImageRenderer
{
    public function render(AbstractInline $inline, ElementRendererInterface $htmlRenderer)
    {
        $element = parent::render($inline, $htmlRenderer);

        $element->setAttribute('class', 'img-responsive');

        return $element;
    }
}
```

😎

**Comment by Devrandomuser** [comment]
@royduin  Any chance to get this working now too?
I'm confused, since the class wasn't found by laravel:

```
root@someone:/var/www/html/proj/app/Extensions/Markdown# ls
ResponsiveImageExtension.php  ResponsiveImageRenderer.php
root@someone:/var/www/html/proj/app/Extensions/Markdown# pwd
/var/www/html/proj/app/Extensions/Markdown
```

markdown.php

    'extensions' => [
        'App\Extensions\Markdown\ResponsiveImageExtension::class',
    ],

Throws:

    Target class [App\Extensions\Markdown\ResponsiveImageExtension::class] does not exist.

**Comment by royduin** [comment]
I've converted it last week but I'm with vacation for a week now. Next week I'll post the updated code

**Comment by Devrandomuser** [comment]
@royduin 

Thanks a lot, I'm confused because the class isn't found? The path is correct and there is no typo at all.

**Comment by GrahamCampbell** [comment]
Remove the single quotes.

**Comment by Devrandomuser** [comment]
@GrahamCampbell  -Thanks, awaiting @royduin for code, seems like `League\CommonMark\Extension\Extension;`has changed a bit.

**Comment by colinodell** [comment]
`League\CommonMark\Extension\Extension` was removed in `league/commonmark` v0.19.  If you're using a newer `1.x` release you should instead implement [`ExtensionInterface`](https://github.com/thephpleague/commonmark/blob/master/src/Extension/ExtensionInterface.php) - see https://commonmark.thephpleague.com/0.19/upgrading/#extensions and https://commonmark.thephpleague.com/1.0/customization/extensions/

**Comment by Devrandomuser** [comment]
@colinodell Already on this, 

ResponsiveImageExtension
```
<?php

namespace App\Extensions\Markdown;

use League\CommonMark\Extension\ExtensionInterface;
use League\CommonMark\ConfigurableEnvironmentInterface;

class ResponsiveImageExtension implements ExtensionInterface
{
    public function register(ConfigurableEnvironmentInterface $env)
    {
        $env->addInlineRenderer(ResponsiveImageRenderer::class);
    }
}
```

Just stucking on `addInlineRenderer()`, what to pass to?

**Comment by Devrandomuser** [comment]
@colinodell @royduin 
Already on this:

ExternalLinkExtension

```
final class ExternalLinkExtension implements ExtensionInterface
{
    public function register(ConfigurableEnvironmentInterface $environment)
    {
        $environment->addInlineRenderer(App\Extensions\Markdown\ImageManipulator::class, new ImageManipulator(), 0);
    }
}
```

ImageManipulator

```
final class ImageManipulator implements InlineRendererInterface, ConfigurationAwareInterface
{
    protected $config;

    public function render(AbstractInline $inline, ElementRendererInterface $htmlRenderer)
    {

         $element = parent::render($inline, $htmlRenderer);
         //magic happens here...
         dd($element);


    }
    
    public function setConfiguration(ConfigurationInterface $configuration)
    {
        $this->config = $configuration;
    }
}
```

How to make sure `render()` method is called?

**Comment by royduin** [comment]
From the ski lift in Westendorf Austria:

```
<?php

namespace App\Extensions\Markdown;

use League\CommonMark\Extension\Extension;
use League\CommonMark\Inline\Element\Image;

class ResponsiveImageExtension extends Extension
{
    protected $renderer;

    public function __construct(ResponsiveImageRenderer $renderer)
    {
        $this->renderer = $renderer;
    }

    public function getInlineRenderers()
    {
        return [Image::class => $this->renderer];
    }
}
```

```
<?php

namespace App\Extensions\Markdown;

use League\CommonMark\ElementRendererInterface;
use League\CommonMark\Inline\Element\AbstractInline;
use League\CommonMark\Inline\Renderer\ImageRenderer;

class ResponsiveImageRenderer extends ImageRenderer
{
    public function render(AbstractInline $inline, ElementRendererInterface $htmlRenderer)
    {
        $element = parent::render($inline, $htmlRenderer);

        $element->setAttribute('class', 'img-responsive');

        return $element;
    }
}
```

**Comment by Devrandomuser** [comment]
@royduin Are you sure the code is for the latest commonmark version? `getInlineRenderers()` isn't defined inside the version at all. Instead I think something like

    $environment->getInlineRenderersForClass();

should be used, just not able to figure out how to use.

**Comment by royduin** [comment]
Updated, sorry and thanks!

**Comment by Devrandomuser** [comment]
@royduin No InlineRenderer anymore?
`render()`and `setConfiguration()`are missing / required.

**Comment by royduin** [comment]
I thought the image is final now so to use a inline renderer you need to copy the image, extending isn't possible anymore. What I've posted worked for me last week. It doesn't work for you?

**Comment by Devrandomuser** [comment]
@royduin Works like a charm, any suggestion on how to use your code to prevent images from being included? I would like to add an extension to prevent images from being included, since they caused abuse and ruin the whole layout of the page sometimes.

**Comment by royduin** [comment]
Remove the node or disable the image component, but I don't have an example for you now because I'm on my phone from vacation.
