### ISSUE TITLE
Table and Raw content

### ISSUE THREAD

**Issue by erikjohnsen6d** [GrahamCampbell/Laravel-Markdown#59]
On v7.0.

Using: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

```
Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3
```

Neither parse down, I just get them wrapped in a `<p>`

Example:
`<p>Markdown | Less | Pretty --- | --- | --- <em>Still</em> | <code>renders</code> | <strong>nicely</strong> 1 | 2 | 3</p>`

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#html
Doesn't appear to work either, and is stripped out.

Also `~~for strikeout~~` doesn't seem to work.

6.1 appears to work for Raw.

**Comment by erikjohnsen6d** [comment]
I'm seeing that the option 'html_input' option defaults to 'strip' but what are the other available values?

**Comment by GrahamCampbell** [comment]
Tables arn't supported in the commonmark spec.
