### ISSUE TITLE
Is it possible to have two sets of options?

### ISSUE THREAD

**Issue by lukewhitehouse** [GrahamCampbell/Laravel-Markdown#60]
Currently I have my `html_input` within the `config/markdown.php` set to true for my own writing ease, however, is there anyway to override these settings for a specific use case. i.e. So writing blog posts means I can use whatever I want, whereas a user writing a comment would only get certain abilities?

Anything like the following available?

``` php
$markdown->options([
    'html_input' => false,
    'allow_unsafe_links' => false
]);

$markdown->convertToHtml($foo);
```

**Comment by lukewhitehouse** [comment]
After looking into this a little more it seems I could use the `config()` helper however, the package doesn't seem to take this into account?

**Comment by GrahamCampbell** [comment]
To edit the config at runtime, you need to interact with the object bound to `markdown.environment`.

**Comment by lucadegasperi** [comment]
I'm having a similar problem, for me some strings would need to be parsed without paragraphs while others do. What do I need to do to achieve something like this?

**Comment by GrahamCampbell** [comment]
> What do I need to do to achieve something like this?

As I said:

> you need to interact with the object bound to markdown.environment
