### ISSUE TITLE
Markdown can't render this {{

### ISSUE THREAD

**Issue by IrsyadAdl** [GrahamCampbell/Laravel-Markdown#64]
I don't why markdown can't render the blade syntax like.

```
<meta name="description" content="{{ $article->teaser }}">
```

The result of it be 

```
<meta name="description" content="">
```

Anyone can answer what's really need to show that ?

**Comment by GrahamCampbell** [comment]
How are you calling it please?

**Comment by GrahamCampbell** [comment]
If it's a blade markdown file, then all we do is pipe the render output through the markdown parser, we don't modify the blade compiling at all.

**Comment by IrsyadAdl** [comment]
Just try like this.
```
<meta name="description" content="{{ $article->teaser }}">
```
I don't know why, but it happened.
```
<meta name="description" content="">
````

**Comment by GrahamCampbell** [comment]
`$article->teaser` must have been the empty string.

**Comment by IrsyadAdl** [comment]
Look. I have a little job. I save the markdown to the database by using textarea. So when I try to show on browser, here's what I can do.
```
{!! Markdown::convertToHtml($article->body) !!}
```

So if you say the teaser is empty, its not actually problem, don't care with that, I just make example code for tutorial. so when I try to show this content, I got the empty from the `{{ }}`. If you don't believe what I was talking about, you can proove it !

**Comment by GrahamCampbell** [comment]
Even if the markdown parser is not working correctly, I'm afraid it's not really an issue with my package. Please take it up with the upstream commonmark package.

If you're using this package to generate html, you will definitely want to look at turning off the safemode flags in the config. They could be causing your content to be deleted.

**Comment by GrahamCampbell** [comment]
In particular, the HTML Input config option as documented at https://github.com/GrahamCampbell/Laravel-Markdown#html-input. As you can see, by default, the html block renderer will delete HTML that it renders by default since the default setting is to "strip": https://github.com/thephpleague/commonmark/blob/0.15.0/src/Block/Renderer/HtmlBlockRenderer.php#L49-L51. You perhaps want to set it to "allow", as found at https://github.com/thephpleague/commonmark/blob/0.15.0/src/Environment.php#L32, though, from the code in the block renderer, setting it to any garbage would actually work I think. :)

**Comment by IrsyadAdl** [comment]
Here's my config file, 
```
    'html_input' => 'allow',
```
But. still. Get the same result. 

Can you see this page, spesipic in the view section
http://parsinta.com/articles/basic-laravel-todo-list-app

**Comment by IrsyadAdl** [comment]
I like this package, very nice then other, I have working along with it, but since I meet it, I really don't understand what the hell actually happened, please clear it brother. I like this package.

**Comment by GrahamCampbell** [comment]
I can't replicate any issues I'm afraid. This package is used in the popular Cachet status page system and there are no reports from any users of that package either.

I don't have time to debug your application there I'm afraid.

**Comment by IrsyadAdl** [comment]
Thank you.

**Comment by italomoralesf** [comment]
How can I make code, to make an article blog with code
I'm using this {!! Markdown::convertToHtml($body) !!}

Example
`<html> //initial document HTML` 

The problem is that it renders the label
