### ISSUE TITLE
target _blank for links

### ISSUE THREAD

**Issue by cmnstmntmn** [GrahamCampbell/Laravel-Markdown#65]
how this can be achieved?

**Comment by GrahamCampbell** [comment]
This isn't really a bug with the package, sorry.

**Comment by cmnstmntmn** [comment]
did i said it's a bug?
i only asked how this can be achieved if is supported by this lib.

**Comment by GrahamCampbell** [comment]
Don't know. This isn't really the place to ask. Sorry.

**Comment by GrahamCampbell** [comment]
This is an issue tracker.

**Comment by Livijn** [comment]
For those of you finding this: https://commonmark.thephpleague.com/2.3/extensions/external-links
