### ISSUE TITLE
Table Extension integration

### ISSUE THREAD

**Issue by joshbruce** [GrahamCampbell/Laravel-Markdown#66]
Thanks for this package.

Running into an issue integrating an extension.

I'm looking to use the [Webuni table extension with Laravel-Markdown](https://github.com/webuni/commonmark-table-extension).

I'm adding the following to the `extensions` array:

`Webuni\CommonMark\TableExtension\TableExtension`

Which does not cause a hard crash; however, it does not render the tables within the Markdown.

Thoughts??

**Comment by GrahamCampbell** [comment]
Thanks, but this is unlikely to be a bug in this package. Please make sure you run the `php artisan config:cache` command.

**Comment by GrahamCampbell** [comment]
If there's still no table's generated, please take it up with the extension author.

**Comment by joshbruce** [comment]
@GrahamCampbell - Thanks. Just wanted to make sure I was using the `extensions` array properly to the best of your knowledge before taking up with the CommonMark extension developer.

This package is just the first in the chain of talking with people. :)

**Comment by joshbruce** [comment]
And, in true technology fashion - after posting an issue - it works...maybe did refresh completely. Cheers.
