### ISSUE TITLE
Parse Markdown before parsing blade syntax?

### ISSUE THREAD

**Issue by tuwannu** [GrahamCampbell/Laravel-Markdown#67]
In `BladeMarkdownEngine::get()` the code is as follow:

    public function get($path, array $data = [])
    {
        $contents = parent::get($path, $data);

        return $this->markdown->convertToHtml($contents);
    }

My `.md.blade.php` contains `@extends('layouts.default')`. This means that `parent::get()` has already parsed my blade template and puts loads of HTML into `$contents`.

When `convertToHtml()`, which supposed to get only Markdown syntax, gets the fully parsed HTML above, it goes crazy and hence lots of `<pre><code>` produced.

Is it possible to specify that markdown content in `.md.blade.php` should be parsed before parsing the rest of blade syntax in that file? If it's not already supported would you welcome a PR that allows that?

**Comment by GrahamCampbell** [comment]
We don't do this because blade syntax itself could be recognised by mistake as markdown, and thus, the file broken.

**Comment by tuwannu** [comment]
Right, I see. I'll see if I could make a blade syntax e.g. @markdown @endmarkdown instead.

**Comment by GrahamCampbell** [comment]
That would work for sure. Would be pretty easy to implement.

**Comment by GrahamCampbell** [comment]
Hmm, well, actually, not quite. Only if there was no other blade in between those annotations.

**Comment by GrahamCampbell** [comment]
Instead, I'd recommend moving your markdown parts to separate .md.blade.php file, then including that from a .blade.php file.

**Comment by tuwannu** [comment]
Just in case anyone wants to reference this. Here is what I ended up implementing. I'm specifically doing this for a release notes page but aiming to reuse the code for other static markdown pages in the future as well...

**routes.php:**

    Route::controller('pages', 'MarkdownPagesController');

**MarkdownPagesController.php:**

    <?php

    class MarkdownPagesController extends \App\Http\Controllers\Controller
    {
        public function getReleaseNotes()
        {
            return $this->markdownView('pages.release-notes');
        }

        protected function markdownView($markdownViewName)
        {
            return view('layouts.markdown', [
                'markdownViewName' => $markdownViewName,
            ]);
        }
    }

**views/layouts/markdown.blade.php:**

    <h1>Default content here</h1>

    <div>
        @include($markdownViewName)
    </div>

**views/pages/release-notes.md:**

    ## My markdown content

The code above generates a page like this for http://localhost/pages/release-notes:

    <h1>Default content here</h1>

    <div>
        <h2>My markdown content</h2>
    </div>
