### ISSUE TITLE
Disable safe mode temporarily

### ISSUE THREAD

**Issue by amraei** [GrahamCampbell/Laravel-Markdown#69]
Setting safe mode to true is good idea for most cases, but sometimes it shouldn't strip HTML tags. I think `convertToHTML` function could have a second argument which let me disable safe mode temporarily.

Is there a possibility to do so right now?

**Comment by GrahamCampbell** [comment]
You can access the environment instance through the IOC, bound to `markdown.environment`, or just the class name, and modify that as you need at runtime. There is no way to do it for a single function call, so probably you could do it with a try finally block, to make sure the environment is restored afterwards. This is a design decision of the commonmark package I'm afraid.

https://github.com/thephpleague/commonmark/blob/master/src/Environment.php

---

Alternatively, to avoid screwing around with this environment instance, you could just build your own "Converter" instance with the config you need at that specific moment, then use that. All the code is at https://github.com/thephpleague/commonmark/tree/master/src.
