### ISSUE TITLE
How to organise classes for an extension?

### ISSUE THREAD

**Issue by Silverspur** [GrahamCampbell/Laravel-Markdown#71]
Hi!

What would be the way to go in order to add an extension to the Markdown supported by the package, without creating a whole new package as in Alt-three/emoji?

I understand how to code the Parser/Renderer classes thanks to the doc, but in a standard Laravel install with laravel-markdown package, where should these classes go?

**Comment by GrahamCampbell** [comment]
There is no convention here. Just do whatever feels natural to you. :)

**Comment by GrahamCampbell** [comment]
If your question is not about class naming/namespacing, and was about how to actually register extensions with this package, then you can do this from the config file, by publishing it.
