### ISSUE TITLE
Break tags in lists

### ISSUE THREAD

**Issue by johnhalsey** [GrahamCampbell/Laravel-Markdown#72]
I'm trying to create a list like this

````
- List item one
- List item 2
````

but when it gets parsed through the `convertToHtml` method it is constantly adding `<br>` tags between all the `<li>` tags like this

````
<ul>
<br>
<li>List item one</li>
<br>
<li>List item 2</li>
<br>
</ul>
````

Any ideas?

**Comment by GrahamCampbell** [comment]
I can't confirm this bug.

Added lists to the test file in our test suite: https://github.com/GrahamCampbell/Laravel-Markdown/commit/338542d44df67f10cc883ffe0fe0dcccd96f8f3f, and the output is as expected:

![image](https://cloud.githubusercontent.com/assets/2829600/25306435/1d7e58bc-2785-11e7-9dc3-9ea5799a9a29.png)
