### ISSUE TITLE
Can I use blade syntax?

### ISSUE THREAD

**Issue by Lawrence-Dawson** [GrahamCampbell/Laravel-Markdown#75]
Hi there, 

I'm using this package, and really like it, but I thought I would be able to use blade syntax within the markdown text, so far i'm having no luck with this, am I attempting the impossible?

Thanks,
Lawrence

**Comment by GrahamCampbell** [comment]
You can use blade syntax in `.md.blade.php` files only. There's an example in the tests: https://github.com/GrahamCampbell/Laravel-Markdown/blob/master/tests/Functional/stubs/bar.md.blade.php.
