### ISSUE TITLE
Suggestion: strip Markdown and api

### ISSUE THREAD

**Issue by saidbakr** [GrahamCampbell/Laravel-Markdown#81]
I could not able to find documentation for the API. I also suggest a method to strip markdown.

**Comment by GrahamCampbell** [comment]
Sorry you missed it. There's a link at the top of the readme to https://github.com/thephpleague/commonmark, that points to http://commonmark.thephpleague.com/. All the docs you need are available there, when combined with the additional docs on our readme.
