### ISSUE TITLE
How can I make my api.md more beautiful after convert or get some style?

### ISSUE THREAD

**Issue by alexli0707** [GrahamCampbell/Laravel-Markdown#83]
Hi,thanks for this awesome project first. I am a developer from python to php,In python ,I can style my markdown doc by pass styles ,but when I use this I cann't find way to style my markdown doc.How can I make my doc more beautiful ,thank you a lot!
Now my doc  looks like that.
<img width="752" alt="30775314-a38e-4f9d-8b20-335eded4136d" src="https://user-images.githubusercontent.com/2542172/29447398-48ef77aa-8424-11e7-94d4-3ab3080cfdff.png">

**Comment by GrahamCampbell** [comment]
Sorry, this is out of scope of bug reports for this package.
