### ISSUE TITLE
markdown doesn't show php code

### ISSUE THREAD

**Issue by maroulu** [GrahamCampbell/Laravel-Markdown#84]
laravel markdown work well with me but when i try to show a php code it shows blank

**Comment by GrahamCampbell** [comment]
Thanks for the report. Could you please provide some more details?

**Comment by maroulu** [comment]
here is my code :
<div>{!! Markdown::convertToHtml($discussion->content) !!}</div>
it works fine with markdown text 
![m1](https://user-images.githubusercontent.com/30576354/29990661-bd24c264-8f74-11e7-9d72-740cf07624fd.PNG)
but when the content has a php code with the tag <?php ?> it shows nothing
![m2](https://user-images.githubusercontent.com/30576354/29990672-d7077a8c-8f74-11e7-9cfc-dca35adf9d37.PNG)

**Comment by GrahamCampbell** [comment]
You cannot pass PHP code into this function. Only pass markdown.
