### ISSUE TITLE
I can't display the table

### ISSUE THREAD

**Issue by syarifmaulanamm** [GrahamCampbell/Laravel-Markdown#85]
Can I display Markdown table. Because when I try to display table I can't.
Thanks

**Comment by GrahamCampbell** [comment]
You can install a markdown table plugin that'll do this. :)

**Comment by GrahamCampbell** [comment]
Leaving this open, to remind me to add docs to the readme, since this is a common request.

**Comment by syarifmaulanamm** [comment]
how to install the plugin? I want install from composer

**Comment by jondwx** [comment]
@syarifmaulanamm 
```php artisan vendor:publish```

install https://github.com/webuni/commonmark-table-extension

```
composer require webuni/commonmark-table-extension
```

config/markdown.php
```
'extensions' => [
    Webuni\CommonMark\TableExtension\TableExtension::class,
],
```

**Comment by GrahamCampbell** [comment]
Thanks @jondwx.
