### ISSUE TITLE
[Question]: config html_input...other possibilities

### ISSUE THREAD

**Issue by joshbruce** [GrahamCampbell/Laravel-Markdown#89]
I have a markdown file being included as a view. I would like to pepper it with some classed HTML.

Cannot figure out how.

**Comment by butabi** [comment]
`strip` - Strip all HTML (equivalent to `'safe' => true`)
`allow` - Allow all HTML input as-is (default value; equivalent to `'safe' => false`)
`escape` - Escape all HTML

https://commonmark.thephpleague.com/configuration/
