### ISSUE TITLE
[Question]: inline rendering

### ISSUE THREAD

**Issue by ducaale** [GrahamCampbell/Laravel-Markdown#91]
is there a method for inline rendering ?
example:
``Markdown::convertToHtml('hello');`` to produce ``hello`` instead of ``<p>hello</p>``

**Comment by jubayed** [comment]
![screenshot-2017-11-1 yarn](https://user-images.githubusercontent.com/9925505/32278439-f77db970-bf3f-11e7-9c4e-816462335231.png)

**Comment by megaxlr** [comment]
This is because the compiler returns a string instead of an object that implements `Htmlable`. 
For now use `{!! !!}` instead of `{{ }}`

**Comment by GrahamCampbell** [comment]
Just wrap it up in an htmlable yourself, or use the unescaped printing. That'd be my recommendation.
