### ISSUE TITLE
Laravel mail button Redirection issue

### ISSUE THREAD

**Issue by jignesh-levaral** [GrahamCampbell/Laravel-Markdown#92]
i have issue with mail button redirection. 

I am using command to send email, where i am setting dynamic app url, which is working,

Example
example.com is my app url

when i am sending mail i am changing it as 

nl.example.com

when i click it redirect to 

http://example.com/email/l/aHR0cDovL25sLmJ1bGRpdC5hcHAvbmwvcmV2aWV3L2xlYWQvNg==/0HeT7VzkZjjIBZFIfAKg4lkWp6SFgMCJ 

where base url should be nl.example.com, so it not redirecting correctly and show page not found 

please let me know how to set app url dynamic when sending mail
Config::set('app.url', 'nl.example.com');

where in footer it showing the right url, button encrypted url ignored 'nl', although i have set it dynamically

![screenshot-mailtrap io-2017-11-10-16-30-30-076](https://user-images.githubusercontent.com/33521382/32655779-1c03df76-c635-11e7-9c3e-dd5845375733.png)

**Comment by GrahamCampbell** [comment]
Sorry, this doesn't seem related to this package?
