### ISSUE TITLE
[Question] Is There a Way to Disable Specific Markdown like Images & Links?

### ISSUE THREAD

**Issue by Laraveldeep** [GrahamCampbell/Laravel-Markdown#94]
I am trying to implement this on a site where public can post. Want to restrict to specific markdown only like bold, italics, bullets etc. (not images and links)

I have published the config via vendor publish but options seems to be limited.

Also what is unsafe link  and how it is determined safe or unsafe?

Thanks!

**Comment by GrahamCampbell** [comment]
> I have published the config via vendor publish but options seems to be limited.

Not via the config. You can do it programmatically by resolving the environment object from the container in your app service provider boot, or by overriding this packages bindings. I'd recommend taking a look at the source for this package and the commonmark package for how to do this.

> Also what is unsafe link and how it is determined safe or unsafe?

Don't know off the top of my head, try checking the commonmark spec, or the php commonmark source code.

**Comment by colinodell** [comment]
> Also what is unsafe link and how it is determined safe or unsafe?

An unsafe link is one where the protocol in the link is `javascript:`, `vbscript:`, `file:`, or `data:`.

(The only exception to this rule is for png, gif, jpeg, or webp images encoded using `data:image` - all other data types are considered "unsafe")

**Comment by GrahamCampbell** [comment]
Thanks @colinodell
