### ISSUE TITLE
Minimum requirement

### ISSUE THREAD

**Issue by rfussien** [GrahamCampbell/Laravel-Markdown#99]
Hello,

First, thanks for your effort (not only for this package).

I'd like to share a thought about the minimum requirement for php.
The php requirement being >=5.4.8 for commonmark and >=5.5.9 for Laravel 5.1 and Laravel-Markdown being a wrapper, that doesn't bring much that justify it requires >= 7.0, would it be any chance to get the requirement down to bring your package available for more people ?
I know that php7 is much better and faster than php5 and every body should switch, but I guess some folks are still using php5 due to legacy code and/or infra (which I'm a part of).

Best,

Rémi

**Comment by GrahamCampbell** [comment]
You can use an older version of this package to get support for older versions of php. :)

**Comment by rfussien** [comment]
True. I didn't think this through... :)

**Comment by GrahamCampbell** [comment]
* The 7.x series supports PHP 5.5.9-7.1 and Laravel 5.1-5.4 (PHP 7.2/7.3 may work, but untested).
* The 8.x series supports PHP 7.0-7.2 and Laravel 5.1-5.5 (PHP 7.3 may work, but untested).

**Comment by rfussien** [comment]
Right. Thanks for your time.
